-- IC Extension Management - Advanced Queries (20)
-- Requirements: 3+ tables, 3+ of: Sub-queries, JOIN, GROUP BY, Window functions, COUNT

-- [RF6] Query 1: Rank participants by average grade across all activities
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, WINDOW (RANK)
SELECT
    sub.DS_NOME_PARTICIPANTE,
    sub.media_global,
    RANK() OVER(ORDER BY sub.media_global DESC) AS RANKING
FROM (
    SELECT
        p.ID_PARTICIPANTE,
        p.DS_NOME_PARTICIPANTE,
        AVG(i.VL_NOTA_AVALIACAO) AS MEDIA_GLOBAL
    FROM TB_PARTICIPANTE p
    JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
    JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
    GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE
) sub;

-- [RF3] Query 2: Find the top 3 projects by total number of certificates issued
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
SELECT DS_NOME_PROJETO, total_certificados
FROM (
    SELECT proj.DS_NOME_PROJETO, COUNT(cert.ID_CERTIFICADO) AS TOTAL_CERTIFICADOS
    FROM TB_PROJETO_EXTENSAO proj
    JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
    GROUP BY proj.DS_NOME_PROJETO
) sub
ORDER BY total_certificados DESC
LIMIT 3;

-- [RF2] Query 3: Activities with participation higher than the average, showing project name
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PROJETO_EXTENSAO
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
WITH AtividadeContagem AS (
    SELECT ID_ATIVIDADE, COUNT(*) AS TOTAL_INSCRITOS
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
)
SELECT a.DS_TITULO_ATIVIDADE, proj.DS_NOME_PROJETO, ac.total_inscritos
FROM TB_ATIVIDADE a
JOIN AtividadeContagem ac ON a.ID_ATIVIDADE = ac.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
WHERE ac.total_inscritos > (SELECT AVG(total_inscritos) FROM AtividadeContagem);

-- [RF7] Query 4: Instructors who never coordinated a project but are allocated to activities
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE, TB_PROJETO_EXTENSAO
-- Funções: SUB-QUERY (NOT EXISTS), JOIN, GROUP BY, COUNT
SELECT
    inst.DS_NOME_INSTRUTOR,
    COUNT(DISTINCT alloc.ID_ATIVIDADE) AS TOTAL_ATIVIDADES_ALOCADAS
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE NOT EXISTS (
    SELECT 1 FROM TB_PROJETO_EXTENSAO proj
    WHERE proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
)
GROUP BY inst.ID_INSTRUTOR, inst.DS_NOME_INSTRUTOR;

-- [RF5] Query 5: Running total of sponsorship contributions per partner with activity names
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (SUM), COUNT
SELECT
    p.DS_NOME_ORGANIZACAO,
    a.DS_TITULO_ATIVIDADE,
    pat.VL_APORTE,
    SUM(pat.VL_APORTE) OVER(PARTITION BY p.ID_PARCEIRO ORDER BY a.ID_ATIVIDADE) AS TOTAL_ACUMULADO,
    COUNT(*) OVER(PARTITION BY p.ID_PARCEIRO) AS TOTAL_PATROCINIOS_PARCEIRO
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE;

-- [RF6] Query 6: Participant grade AS PERCENTAGE of max grade, only for activities with >5 enrollments
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW, SUB-QUERY
SELECT
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    i.VL_NOTA_AVALIACAO,
    (i.VL_NOTA_AVALIACAO / MAX(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE)) * 100 AS PERC_MAX_NOTA
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
    HAVING COUNT(*) > 5
);

-- [RF7] Query 7: Projects where the coordinator also teaches, only projects with >5 activities
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT proj.DS_NOME_PROJETO, (SELECT COUNT(*) FROM TB_ATIVIDADE WHERE ID_PROJ_VINCULADO = proj.ID_PROJETO) AS TOTAL_ATIVIDADES
FROM TB_PROJETO_EXTENSAO proj
WHERE EXISTS (
    SELECT 1 FROM TB_ATIVIDADE a
    JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
    WHERE a.ID_PROJ_VINCULADO = proj.ID_PROJETO
    AND alloc.ID_INSTRUTOR = proj.ID_INSTR_COORDENADOR
)
AND proj.ID_PROJETO IN (
    SELECT ID_PROJ_VINCULADO
    FROM TB_ATIVIDADE
    GROUP BY ID_PROJ_VINCULADO
    HAVING COUNT(*) > 5
);

-- [RF7] Query 8: Projects with more than average 'ALUNO' participants
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, RL_MEMBRO_PROJETO, TB_PARTICIPANTE
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT proj.DS_NOME_PROJETO, COUNT(p.ID_PARTICIPANTE) AS TOTAL_ALUNOS
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
JOIN TB_PARTICIPANTE p ON mem.ID_PARTICIPANTE = p.ID_PARTICIPANTE
WHERE p.TP_VINCULO_INST = 'ALUNO'
GROUP BY proj.DS_NOME_PROJETO
HAVING COUNT(p.ID_PARTICIPANTE) > (
    SELECT AVG(alunos_count) FROM (
        SELECT COUNT(p2.ID_PARTICIPANTE) AS ALUNOS_COUNT
        FROM RL_MEMBRO_PROJETO mem2
        JOIN TB_PARTICIPANTE p2 ON mem2.ID_PARTICIPANTE = p2.ID_PARTICIPANTE
        WHERE p2.TP_VINCULO_INST = 'ALUNO'
        GROUP BY mem2.ID_PROJETO
    ) sub
);

-- [RF1] Query 9: Activities with more than 1 instructor and also have a partner sponsor
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR, RL_PATROCINIO_EVENTO
-- Funções: SUB-QUERY (IN + EXISTS), GROUP BY, COUNT (HAVING)
SELECT DS_TITULO_ATIVIDADE
FROM TB_ATIVIDADE a
WHERE ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_ALOCACAO_INSTRUTOR GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 1
) AND EXISTS (
    SELECT 1 FROM RL_PATROCINIO_EVENTO pat WHERE pat.ID_ATIVIDADE = a.ID_ATIVIDADE
);

-- [RF5] Query 10: Month-over-month growth of projects alongside total enrollments per project creation month
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_INSCRICAO_HISTORICO
-- Funções: JOIN, GROUP BY, WINDOW (SUM), COUNT
SELECT
    DATE_TRUNC('month', proj.DT_CRIACAO) AS MES_CRIACAO,
    COUNT(DISTINCT proj.ID_PROJETO) AS PROJETOS_NO_MES,
    COUNT(DISTINCT i.ID_INSCRICAO) AS TOTAL_INSCRICOES,
    SUM(COUNT(DISTINCT proj.ID_PROJETO)) OVER(ORDER BY DATE_TRUNC('month', proj.DT_CRIACAO)) AS PROJETOS_ACUMULADOS,
    COUNT(DISTINCT proj.ID_PROJETO) - COALESCE(LAG(COUNT(DISTINCT proj.ID_PROJETO)) OVER(ORDER BY DATE_TRUNC('month', proj.DT_CRIACAO)), 0) AS CRESCIMENTO_MENSAL
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
GROUP BY DATE_TRUNC('month', proj.DT_CRIACAO);

-- [RF4] Query 11: Find the activity with the highest average satisfaction rating
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK
-- Funções: SUB-QUERY, JOIN, GROUP BY
SELECT DS_TITULO_ATIVIDADE, media_satisfacao
FROM (
    SELECT a.DS_TITULO_ATIVIDADE, AVG(f.VL_NOTA_SATISFACAO) AS MEDIA_SATISFACAO
    FROM TB_ATIVIDADE a
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
    GROUP BY a.DS_TITULO_ATIVIDADE
) sub
ORDER BY media_satisfacao DESC
LIMIT 1;

-- [RF3] Query 12: Participants who have a certificate for every activity, with certificate count
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: SUB-QUERY (NOT EXISTS), JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE, COUNT(c.ID_CERTIFICADO) AS TOTAL_CERTIFICADOS
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_EMISSAO_CERTIFICADO c ON i.ID_INSCRICAO = c.ID_INSCRICAO
WHERE NOT EXISTS (
    SELECT 1 FROM RL_INSCRICAO_HISTORICO i2
    LEFT JOIN TB_EMISSAO_CERTIFICADO c2 ON i2.ID_INSCRICAO = c2.ID_INSCRICAO
    WHERE i2.ID_PARTICIPANTE = p.ID_PARTICIPANTE AND c2.ID_CERTIFICADO IS NULL
)
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE;

-- [RF2] Query 13: Super-participants (>5 enrollments) with activity details
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE, COUNT(i.ID_INSCRICAO) AS TOTAL_INSCRICOES
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE p.ID_PARTICIPANTE IN (
    SELECT i2.ID_PARTICIPANTE
    FROM RL_INSCRICAO_HISTORICO i2
    GROUP BY i2.ID_PARTICIPANTE
    HAVING COUNT(i2.ID_INSCRICAO) > 2
)
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE;

-- [RF1] Query 14: Projects and average workload, only projects above overall average workload
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT
    proj.DS_NOME_PROJETO,
    AVG(alloc.VL_CARGA_HORARIA) AS AVG_WORKLOAD,
    COUNT(DISTINCT a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
GROUP BY proj.ID_PROJETO, proj.DS_NOME_PROJETO
HAVING AVG(alloc.VL_CARGA_HORARIA) > (
    SELECT AVG(VL_CARGA_HORARIA) FROM RL_ALOCACAO_INSTRUTOR
);

-- [RF2] Query 15: First activity date for each participant, only those enrolled in >2 activities
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (FIRST_VALUE), SUB-QUERY
SELECT DISTINCT
    p.DS_NOME_PARTICIPANTE,
    FIRST_VALUE(a.DT_REALIZACAO) OVER(PARTITION BY p.ID_PARTICIPANTE ORDER BY a.DT_REALIZACAO) AS PRIMEIRA_ATIVIDADE
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE p.ID_PARTICIPANTE IN (
    SELECT i2.ID_PARTICIPANTE
    FROM RL_INSCRICAO_HISTORICO i2
    GROUP BY i2.ID_PARTICIPANTE
    HAVING COUNT(DISTINCT i2.ID_ATIVIDADE) > 1
);

-- [RF1] Query 16: Count activities by instructor specialty (>= 2 activities), ordered by highest count
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY, ORDER BY
SELECT inst.DS_ESPECIALIDADE, COUNT(DISTINCT a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE inst.DS_ESPECIALIDADE IN (
    SELECT inst2.DS_ESPECIALIDADE
    FROM TB_INSTRUTOR inst2
    JOIN RL_ALOCACAO_INSTRUTOR alloc2 ON inst2.ID_INSTRUTOR = alloc2.ID_INSTRUTOR
    GROUP BY inst2.DS_ESPECIALIDADE
    HAVING COUNT(DISTINCT alloc2.ID_ATIVIDADE) >= 2
)
GROUP BY inst.DS_ESPECIALIDADE
ORDER BY total_atividades DESC;

-- [RF4] Query 17: Participant with lowest feedback score in a highly attended activity (>20 people)
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK, TB_ATIVIDADE
-- Funções: SUB-QUERY, JOIN, GROUP BY (in sub-query), COUNT (HAVING)
SELECT p.DS_NOME_PARTICIPANTE, f.VL_NOTA_SATISFACAO, a.DS_TITULO_ATIVIDADE
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 20
)
ORDER BY f.VL_NOTA_SATISFACAO ASC
LIMIT 1;

-- [RF2] Query 18: Recent activities with enrollment counts, compared to overall average
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PARTICIPANTE
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
WITH RecentActivities AS (
    SELECT * FROM TB_ATIVIDADE WHERE DT_REALIZACAO >= CURRENT_DATE - INTERVAL '6 months'
)
SELECT
    ra.DS_TITULO_ATIVIDADE,
    ra.DT_REALIZACAO,
    COUNT(i.ID_INSCRICAO) AS TOTAL_INSCRITOS
FROM RecentActivities ra
JOIN RL_INSCRICAO_HISTORICO i ON ra.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON i.ID_PARTICIPANTE = p.ID_PARTICIPANTE
GROUP BY ra.ID_ATIVIDADE, ra.DS_TITULO_ATIVIDADE, ra.DT_REALIZACAO
HAVING COUNT(i.ID_INSCRICAO) > (
    SELECT AVG(cnt) FROM (
        SELECT COUNT(*) AS CNT FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE
    ) avg_sub
);

-- [RF5] Query 19: Partners who sponsor activities in more than one project, with total value
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT (HAVING), SUB-QUERY
SELECT p.DS_NOME_ORGANIZACAO, 
       (SELECT SUM(VL_APORTE) FROM RL_PATROCINIO_EVENTO pat2 WHERE pat2.ID_PARCEIRO = p.ID_PARCEIRO) AS TOTAL_APORTADO
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY p.ID_PARCEIRO, p.DS_NOME_ORGANIZACAO
HAVING COUNT(DISTINCT a.ID_PROJ_VINCULADO) > 1;

-- [RF6] Query 20: Difference between participant grade and activity average, for activities with >10 enrollments
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (AVG), SUB-QUERY
SELECT
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    i.VL_NOTA_AVALIACAO,
    i.VL_NOTA_AVALIACAO - AVG(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE) AS DIFF_PARA_MEDIA
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
    HAVING COUNT(*) > 10
);
