-- IC Extension Management Database - Audit Triggers
-- Compliant with MAD1 Rules
-- DBMS: PostgreSQL

-- 1. Create Audit Tables (TA_)

CREATE TABLE TA_TB_ATIVIDADE (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_ATIVIDADE INT NOT NULL,
    DS_TITULO_ATIVIDADE VARCHAR(150),
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE,
    ID_PROJ_VINCULADO INT,
    TP_OPERACAO CHAR(1) NOT NULL, -- I/U/D
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_INSCRICAO_HISTORICO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL,
    ID_PARTICIPANTE INT,
    ID_ATIVIDADE INT,
    ST_PRESENCA VARCHAR(20),
    VL_NOTA_AVALIACAO DECIMAL(4,2),
    TP_OPERACAO CHAR(1) NOT NULL, -- I/U/D
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_PARTICIPANTE (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    DS_NOME_PARTICIPANTE VARCHAR(150),
    DS_EMAIL_CONTATO VARCHAR(100),
    TP_VINCULO_INST VARCHAR(30),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_PROJETO_EXTENSAO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PROJETO INT NOT NULL,
    DS_NOME_PROJETO VARCHAR(150),
    DT_CRIACAO DATE,
    ID_INSTR_COORDENADOR INT,
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_INSTRUTOR (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_INSTRUTOR INT NOT NULL,
    DS_NOME_INSTRUTOR VARCHAR(150),
    DS_ESPECIALIDADE VARCHAR(100),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_PARCEIRO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARCEIRO INT NOT NULL,
    DS_NOME_ORGANIZACAO VARCHAR(150),
    TP_PARCEIRO VARCHAR(30),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_EMISSAO_CERTIFICADO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_CERTIFICADO INT NOT NULL,
    ID_INSCRICAO INT,
    DT_EMISSAO DATE,
    CD_AUTENTICIDADE VARCHAR(60),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_REGISTRO_FEEDBACK (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_FEEDBACK INT NOT NULL,
    ID_INSCRICAO INT,
    VL_NOTA_SATISFACAO INT,
    DS_COMENTARIO_ABERTO TEXT,
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_ALOCACAO_INSTRUTOR (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT,
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_PATROCINIO_EVENTO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_MEMBRO_PROJETO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

-- 2. Create Audit Functions

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_ATIVIDADE()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_ATIVIDADE, OLD.DS_TITULO_ATIVIDADE, OLD.DS_CONTEUDO_PROG, OLD.DT_REALIZACAO, OLD.ID_PROJ_VINCULADO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.DS_TITULO_ATIVIDADE, NEW.DS_CONTEUDO_PROG, NEW.DT_REALIZACAO, NEW.ID_PROJ_VINCULADO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.DS_TITULO_ATIVIDADE, NEW.DS_CONTEUDO_PROG, NEW.DT_REALIZACAO, NEW.ID_PROJ_VINCULADO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_INSCR_HIST()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_INSCRICAO, OLD.ID_PARTICIPANTE, OLD.ID_ATIVIDADE, OLD.ST_PRESENCA, OLD.VL_NOTA_AVALIACAO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSCRICAO, NEW.ID_PARTICIPANTE, NEW.ID_ATIVIDADE, NEW.ST_PRESENCA, NEW.VL_NOTA_AVALIACAO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSCRICAO, NEW.ID_PARTICIPANTE, NEW.ID_ATIVIDADE, NEW.ST_PRESENCA, NEW.VL_NOTA_AVALIACAO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_PARTICIPANTE()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_PARTICIPANTE (ID_PARTICIPANTE, DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARTICIPANTE, OLD.DS_NOME_PARTICIPANTE, OLD.DS_EMAIL_CONTATO, OLD.TP_VINCULO_INST, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_PARTICIPANTE (ID_PARTICIPANTE, DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.DS_NOME_PARTICIPANTE, NEW.DS_EMAIL_CONTATO, NEW.TP_VINCULO_INST, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_PARTICIPANTE (ID_PARTICIPANTE, DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.DS_NOME_PARTICIPANTE, NEW.DS_EMAIL_CONTATO, NEW.TP_VINCULO_INST, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_PROJETO_EXTENSAO (ID_PROJETO, DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PROJETO, OLD.DS_NOME_PROJETO, OLD.DT_CRIACAO, OLD.ID_INSTR_COORDENADOR, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_PROJETO_EXTENSAO (ID_PROJETO, DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PROJETO, NEW.DS_NOME_PROJETO, NEW.DT_CRIACAO, NEW.ID_INSTR_COORDENADOR, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_PROJETO_EXTENSAO (ID_PROJETO, DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PROJETO, NEW.DS_NOME_PROJETO, NEW.DT_CRIACAO, NEW.ID_INSTR_COORDENADOR, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_INSTRUTOR()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_INSTRUTOR (ID_INSTRUTOR, DS_NOME_INSTRUTOR, DS_ESPECIALIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_INSTRUTOR, OLD.DS_NOME_INSTRUTOR, OLD.DS_ESPECIALIDADE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_INSTRUTOR (ID_INSTRUTOR, DS_NOME_INSTRUTOR, DS_ESPECIALIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSTRUTOR, NEW.DS_NOME_INSTRUTOR, NEW.DS_ESPECIALIDADE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_INSTRUTOR (ID_INSTRUTOR, DS_NOME_INSTRUTOR, DS_ESPECIALIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSTRUTOR, NEW.DS_NOME_INSTRUTOR, NEW.DS_ESPECIALIDADE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_PARCEIRO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_PARCEIRO (ID_PARCEIRO, DS_NOME_ORGANIZACAO, TP_PARCEIRO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARCEIRO, OLD.DS_NOME_ORGANIZACAO, OLD.TP_PARCEIRO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_PARCEIRO (ID_PARCEIRO, DS_NOME_ORGANIZACAO, TP_PARCEIRO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.DS_NOME_ORGANIZACAO, NEW.TP_PARCEIRO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_PARCEIRO (ID_PARCEIRO, DS_NOME_ORGANIZACAO, TP_PARCEIRO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.DS_NOME_ORGANIZACAO, NEW.TP_PARCEIRO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_EMISSAO_CERTIFICADO (ID_CERTIFICADO, ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_CERTIFICADO, OLD.ID_INSCRICAO, OLD.DT_EMISSAO, OLD.CD_AUTENTICIDADE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_EMISSAO_CERTIFICADO (ID_CERTIFICADO, ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_CERTIFICADO, NEW.ID_INSCRICAO, NEW.DT_EMISSAO, NEW.CD_AUTENTICIDADE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_EMISSAO_CERTIFICADO (ID_CERTIFICADO, ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_CERTIFICADO, NEW.ID_INSCRICAO, NEW.DT_EMISSAO, NEW.CD_AUTENTICIDADE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_REGISTRO_FEEDBACK (ID_FEEDBACK, ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_FEEDBACK, OLD.ID_INSCRICAO, OLD.VL_NOTA_SATISFACAO, OLD.DS_COMENTARIO_ABERTO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_REGISTRO_FEEDBACK (ID_FEEDBACK, ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_FEEDBACK, NEW.ID_INSCRICAO, NEW.VL_NOTA_SATISFACAO, NEW.DS_COMENTARIO_ABERTO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_REGISTRO_FEEDBACK (ID_FEEDBACK, ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_FEEDBACK, NEW.ID_INSCRICAO, NEW.VL_NOTA_SATISFACAO, NEW.DS_COMENTARIO_ABERTO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_ATIVIDADE, OLD.ID_INSTRUTOR, OLD.VL_CARGA_HORARIA, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.ID_INSTRUTOR, NEW.VL_CARGA_HORARIA, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.ID_INSTRUTOR, NEW.VL_CARGA_HORARIA, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARCEIRO, OLD.ID_ATIVIDADE, OLD.VL_APORTE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.ID_ATIVIDADE, NEW.VL_APORTE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.ID_ATIVIDADE, NEW.VL_APORTE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARTICIPANTE, OLD.ID_PROJETO, OLD.TP_PAPEL_ATUACAO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.ID_PROJETO, NEW.TP_PAPEL_ATUACAO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.ID_PROJETO, NEW.TP_PAPEL_ATUACAO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 3. Create Triggers (TG_A_[I/U/D]_)

CREATE TRIGGER TG_A_I_TB_ATIVIDADE
AFTER INSERT ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_U_TB_ATIVIDADE
AFTER UPDATE ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_D_TB_ATIVIDADE
AFTER DELETE ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_I_RL_INSCRICAO
AFTER INSERT ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_INSCR_HIST();

CREATE TRIGGER TG_A_U_RL_INSCRICAO
AFTER UPDATE ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_INSCR_HIST();

CREATE TRIGGER TG_A_D_RL_INSCRICAO
AFTER DELETE ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_INSCR_HIST();

CREATE TRIGGER TG_A_I_TB_PARTICIPANTE
AFTER INSERT ON TB_PARTICIPANTE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARTICIPANTE();

CREATE TRIGGER TG_A_U_TB_PARTICIPANTE
AFTER UPDATE ON TB_PARTICIPANTE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARTICIPANTE();

CREATE TRIGGER TG_A_D_TB_PARTICIPANTE
AFTER DELETE ON TB_PARTICIPANTE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARTICIPANTE();

CREATE TRIGGER TG_A_I_TB_PROJETO_EXTENSAO
AFTER INSERT ON TB_PROJETO_EXTENSAO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO();

CREATE TRIGGER TG_A_U_TB_PROJETO_EXTENSAO
AFTER UPDATE ON TB_PROJETO_EXTENSAO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO();

CREATE TRIGGER TG_A_D_TB_PROJETO_EXTENSAO
AFTER DELETE ON TB_PROJETO_EXTENSAO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO();

CREATE TRIGGER TG_A_I_TB_INSTRUTOR
AFTER INSERT ON TB_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_INSTRUTOR();

CREATE TRIGGER TG_A_U_TB_INSTRUTOR
AFTER UPDATE ON TB_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_INSTRUTOR();

CREATE TRIGGER TG_A_D_TB_INSTRUTOR
AFTER DELETE ON TB_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_INSTRUTOR();

CREATE TRIGGER TG_A_I_TB_PARCEIRO
AFTER INSERT ON TB_PARCEIRO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARCEIRO();

CREATE TRIGGER TG_A_U_TB_PARCEIRO
AFTER UPDATE ON TB_PARCEIRO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARCEIRO();

CREATE TRIGGER TG_A_D_TB_PARCEIRO
AFTER DELETE ON TB_PARCEIRO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARCEIRO();

CREATE TRIGGER TG_A_I_TB_EMISSAO_CERTIFICADO
AFTER INSERT ON TB_EMISSAO_CERTIFICADO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO();

CREATE TRIGGER TG_A_U_TB_EMISSAO_CERTIFICADO
AFTER UPDATE ON TB_EMISSAO_CERTIFICADO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO();

CREATE TRIGGER TG_A_D_TB_EMISSAO_CERTIFICADO
AFTER DELETE ON TB_EMISSAO_CERTIFICADO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO();

CREATE TRIGGER TG_A_I_TB_REGISTRO_FEEDBACK
AFTER INSERT ON TB_REGISTRO_FEEDBACK
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK();

CREATE TRIGGER TG_A_U_TB_REGISTRO_FEEDBACK
AFTER UPDATE ON TB_REGISTRO_FEEDBACK
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK();

CREATE TRIGGER TG_A_D_TB_REGISTRO_FEEDBACK
AFTER DELETE ON TB_REGISTRO_FEEDBACK
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK();

CREATE TRIGGER TG_A_I_RL_ALOCACAO_INSTRUTOR
AFTER INSERT ON RL_ALOCACAO_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR();

CREATE TRIGGER TG_A_U_RL_ALOCACAO_INSTRUTOR
AFTER UPDATE ON RL_ALOCACAO_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR();

CREATE TRIGGER TG_A_D_RL_ALOCACAO_INSTRUTOR
AFTER DELETE ON RL_ALOCACAO_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR();

CREATE TRIGGER TG_A_I_RL_PATROCINIO_EVENTO
AFTER INSERT ON RL_PATROCINIO_EVENTO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO();

CREATE TRIGGER TG_A_U_RL_PATROCINIO_EVENTO
AFTER UPDATE ON RL_PATROCINIO_EVENTO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO();

CREATE TRIGGER TG_A_D_RL_PATROCINIO_EVENTO
AFTER DELETE ON RL_PATROCINIO_EVENTO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO();

CREATE TRIGGER TG_A_I_RL_MEMBRO_PROJETO
AFTER INSERT ON RL_MEMBRO_PROJETO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO();

CREATE TRIGGER TG_A_U_RL_MEMBRO_PROJETO
AFTER UPDATE ON RL_MEMBRO_PROJETO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO();

CREATE TRIGGER TG_A_D_RL_MEMBRO_PROJETO
AFTER DELETE ON RL_MEMBRO_PROJETO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO();
