-- IC Extension Management Database - Audit Triggers
-- Compliant with MAD1 Rules
-- DBMS: PostgreSQL

-- 1. Create Audit Tables (TA_)

CREATE TABLE TA_TB_ATIVIDADE (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_ATIVIDADE INT NOT NULL,
    DS_TITULO_ATIVIDADE VARCHAR(150),
    TP_OPERACAO CHAR(1) NOT NULL, -- I/U/D
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_INSCRICAO_HISTORICO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL,
    ST_PRESENCA VARCHAR(20),
    VL_NOTA_AVALIACAO DECIMAL(4,2),
    TP_OPERACAO CHAR(1) NOT NULL, -- I/U/D
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

-- 2. Create Audit Functions

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_ATIVIDADE()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_ATIVIDADE, OLD.DS_TITULO_ATIVIDADE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.DS_TITULO_ATIVIDADE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.DS_TITULO_ATIVIDADE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_INSCRICAO_HISTORICO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_INSCRICAO, OLD.ST_PRESENCA, OLD.VL_NOTA_AVALIACAO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSCRICAO, NEW.ST_PRESENCA, NEW.VL_NOTA_AVALIACAO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSCRICAO, NEW.ST_PRESENCA, NEW.VL_NOTA_AVALIACAO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 3. Create Triggers (TG_A_[I/U/D]_)

CREATE TRIGGER TG_A_IUD_TB_ATIVIDADE
AFTER INSERT OR UPDATE OR DELETE ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_IUD_RL_INSCRICAO
AFTER INSERT OR UPDATE OR DELETE ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_INSCRICAO_HISTORICO();
