-- IC Extension Management Database Initialization
-- Physical Schema based on Logical Model
-- DBMS: PostgreSQL

CREATE EXTENSION IF NOT EXISTS citext;

-- 1. Base Tables (TB_)

CREATE TABLE TB_INSTRUTOR (
    ID_INSTRUTOR SERIAL,
    DS_NOME_INSTRUTOR VARCHAR(150) NOT NULL,
    DS_ESPECIALIDADE VARCHAR(100),
    CONSTRAINT PK_TB_INSTRUTOR PRIMARY KEY (ID_INSTRUTOR)
);

CREATE TABLE TB_PROJETO_EXTENSAO (
    ID_PROJETO SERIAL,
    DS_NOME_PROJETO VARCHAR(150) NOT NULL,
    DT_CRIACAO DATE NOT NULL CONSTRAINT DF_PROJETO_CRIACAO DEFAULT CURRENT_DATE,
    ID_INSTR_COORDENADOR INT NOT NULL,
    CONSTRAINT PK_TB_PROJETO_EXTENSAO PRIMARY KEY (ID_PROJETO),
    CONSTRAINT UQ_TB_PROJETO_EXTENSAO_NOME UNIQUE (DS_NOME_PROJETO),
    CONSTRAINT FK_TB_INSTRUTOR_TB_PROJETO_EXTENSAO_COORD FOREIGN KEY (ID_INSTR_COORDENADOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR) ON DELETE RESTRICT
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL,
    DS_TITULO_ATIVIDADE VARCHAR(150) NOT NULL,
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE NOT NULL,
    ID_PROJ_VINCULADO INT,
    CONSTRAINT PK_TB_ATIVIDADE PRIMARY KEY (ID_ATIVIDADE),
    CONSTRAINT CK_TB_ATIVIDADE_DT_REALIZACAO CHECK (DT_REALIZACAO >= '2000-01-01'),
    CONSTRAINT FK_TB_PROJETO_EXTENSAO_TB_ATIVIDADE_PROJ FOREIGN KEY (ID_PROJ_VINCULADO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO) ON DELETE SET NULL
);

CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE SERIAL,
    DS_NOME_PARTICIPANTE VARCHAR(150) NOT NULL,
    DS_EMAIL_CONTATO CITEXT NOT NULL,
    TP_VINCULO_INST VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TB_PARTICIPANTE PRIMARY KEY (ID_PARTICIPANTE),
    CONSTRAINT UK_PARTICIPANTE_EMAIL UNIQUE (DS_EMAIL_CONTATO),
    CONSTRAINT CK_TB_PARTICIPANTE_EMAIL CHECK (DS_EMAIL_CONTATO LIKE '%@%'),
    CONSTRAINT CK_TB_PARTICIPANTE_VINCULO CHECK (TP_VINCULO_INST IN ('ALUNO', 'COMUNIDADE', 'SERVIDOR'))
);

CREATE TABLE TB_PARCEIRO (
    ID_PARCEIRO SERIAL,
    DS_NOME_ORGANIZACAO CITEXT NOT NULL,
    TP_PARCEIRO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TB_PARCEIRO PRIMARY KEY (ID_PARCEIRO),
    CONSTRAINT UQ_TB_PARCEIRO_NOME UNIQUE (DS_NOME_ORGANIZACAO),
    CONSTRAINT CK_TB_PARCEIRO_TIPO CHECK (TP_PARCEIRO IN ('Empresa Privada', 'ONG', 'Órgão Público'))
);

-- 2. Associative Tables (RL_)

CREATE TABLE RL_INSCRICAO_HISTORICO (
    ID_INSCRICAO SERIAL,
    ID_PARTICIPANTE INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    ST_PRESENCA VARCHAR(20) NOT NULL,
    VL_NOTA_AVALIACAO DECIMAL(4,2),
    CONSTRAINT PK_RL_INSCRICAO_HISTORICO PRIMARY KEY (ID_INSCRICAO),
    CONSTRAINT FK_TB_PARTICIPANTE_RL_INSCRICAO_HISTORICO_PART FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_TB_ATIVIDADE_RL_INSCRICAO_HISTORICO_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT CK_INSCRICAO_PRESENCA CHECK (ST_PRESENCA IN ('PRESENTE', 'AUSENTE')),
    CONSTRAINT CK_INSCRICAO_NOTA CHECK (VL_NOTA_AVALIACAO BETWEEN 0 AND 10),
    CONSTRAINT UK_INSCRICAO_UNICA UNIQUE (ID_PARTICIPANTE, ID_ATIVIDADE)
);

CREATE TABLE TB_EMISSAO_CERTIFICADO (
    ID_CERTIFICADO SERIAL,
    ID_INSCRICAO INT NOT NULL,
    DT_EMISSAO DATE NOT NULL CONSTRAINT DF_CERTIFICADO_EMISSAO DEFAULT CURRENT_DATE,
    CD_AUTENTICIDADE VARCHAR(60) NOT NULL,
    CONSTRAINT PK_TB_EMISSAO_CERTIFICADO PRIMARY KEY (ID_CERTIFICADO),
    CONSTRAINT UK_CERTIFICADO_INSCRICAO UNIQUE (ID_INSCRICAO),
    CONSTRAINT UK_CERTIFICADO_AUTENTICIDADE UNIQUE (CD_AUTENTICIDADE),
    CONSTRAINT FK_RL_INSCRICAO_HISTORICO_TB_EMISSAO_CERTIFICADO_INSC FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE TB_REGISTRO_FEEDBACK (
    ID_FEEDBACK SERIAL,
    ID_INSCRICAO INT NOT NULL,
    VL_NOTA_SATISFACAO INT NOT NULL,
    DS_COMENTARIO_ABERTO TEXT,
    CONSTRAINT PK_TB_REGISTRO_FEEDBACK PRIMARY KEY (ID_FEEDBACK),
    CONSTRAINT UK_FEEDBACK_INSCRICAO UNIQUE (ID_INSCRICAO),
    CONSTRAINT CK_FEEDBACK_SATISFACAO CHECK (VL_NOTA_SATISFACAO BETWEEN 1 AND 5),
    CONSTRAINT FK_RL_INSCRICAO_HISTORICO_TB_REGISTRO_FEEDBACK_INSC FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE RL_ALOCACAO_INSTRUTOR (
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT NOT NULL,
    CONSTRAINT PK_RL_ALOCACAO_INSTRUTOR PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR),
    CONSTRAINT FK_TB_ATIVIDADE_RL_ALOCACAO_INSTRUTOR_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT FK_TB_INSTRUTOR_RL_ALOCACAO_INSTRUTOR_INST FOREIGN KEY (ID_INSTRUTOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR),
    CONSTRAINT CK_ALOCACAO_CARGA CHECK (VL_CARGA_HORARIA > 0)
);

CREATE TABLE RL_PATROCINIO_EVENTO (
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    CONSTRAINT PK_RL_PATROCINIO_EVENTO PRIMARY KEY (ID_PARCEIRO, ID_ATIVIDADE),
    CONSTRAINT FK_TB_PARCEIRO_RL_PATROCINIO_EVENTO_PARC FOREIGN KEY (ID_PARCEIRO) REFERENCES TB_PARCEIRO(ID_PARCEIRO),
    CONSTRAINT FK_TB_ATIVIDADE_RL_PATROCINIO_EVENTO_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT CK_PATROCINIO_APORTE CHECK (VL_APORTE > 0)
);

CREATE TABLE RL_MEMBRO_PROJETO (
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_RL_MEMBRO_PROJETO PRIMARY KEY (ID_PARTICIPANTE, ID_PROJETO),
    CONSTRAINT FK_TB_PARTICIPANTE_RL_MEMBRO_PROJETO_PART FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_TB_PROJETO_EXTENSAO_RL_MEMBRO_PROJETO_PROJ FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);
