-- IC Extension Management Database Initialization
-- Physical Schema based on Logical Model
-- DBMS: PostgreSQL

-- 1. Base Tables (TB_)

CREATE TABLE TB_INSTRUTOR (
    ID_INSTRUTOR SERIAL PRIMARY KEY,
    DS_NOME_INSTRUTOR VARCHAR(150) NOT NULL,
    DS_ESPECIALIDADE VARCHAR(100)
);

CREATE TABLE TB_PROJETO_EXTENSAO (
    ID_PROJETO SERIAL PRIMARY KEY,
    DS_NOME_PROJETO VARCHAR(150) NOT NULL,
    DT_CRIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_INSTR_COORDENADOR INT NOT NULL,
    CONSTRAINT FK_PROJETO_COORDENADOR FOREIGN KEY (ID_INSTR_COORDENADOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR)
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL PRIMARY KEY,
    DS_TITULO_ATIVIDADE VARCHAR(150) NOT NULL,
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_PROJ_VINCULADO INT,
    CONSTRAINT FK_ATIVIDADE_PROJETO FOREIGN KEY (ID_PROJ_VINCULADO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);

CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE SERIAL PRIMARY KEY,
    DS_NOME_PARTICIPANTE VARCHAR(150) NOT NULL,
    DS_EMAIL_CONTATO VARCHAR(100) NOT NULL,
    TP_VINCULO_INST VARCHAR(30) NOT NULL
);

CREATE TABLE TB_PARCEIRO (
    ID_PARCEIRO SERIAL PRIMARY KEY,
    DS_NOME_ORGANIZACAO VARCHAR(150) NOT NULL,
    TP_PARCEIRO VARCHAR(30) NOT NULL
);

-- 2. Associative Tables (RL_)

CREATE TABLE RL_INSCRICAO_HISTORICO (
    ID_INSCRICAO SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    ST_PRESENCA VARCHAR(20) NOT NULL CHECK (ST_PRESENCA IN ('PRESENTE', 'AUSENTE')),
    VL_NOTA_AVALIACAO DECIMAL(4,2) CHECK (VL_NOTA_AVALIACAO BETWEEN 0 AND 10),
    CONSTRAINT FK_INSCRICAO_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_INSCRICAO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE TB_EMISSAO_CERTIFICADO (
    ID_CERTIFICADO SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL UNIQUE,
    DT_EMISSAO DATE NOT NULL DEFAULT CURRENT_DATE,
    CD_AUTENTICIDADE VARCHAR(60) NOT NULL UNIQUE,
    CONSTRAINT FK_CERTIFICADO_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE TB_REGISTRO_FEEDBACK (
    ID_FEEDBACK SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL UNIQUE,
    VL_NOTA_SATISFACAO INT NOT NULL CHECK (VL_NOTA_SATISFACAO BETWEEN 1 AND 5),
    DS_COMENTARIO_ABERTO TEXT,
    CONSTRAINT FK_FEEDBACK_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE RL_ALOCACAO_INSTRUTOR (
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT NOT NULL,
    PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR),
    CONSTRAINT FK_ALOCACAO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT FK_ALOCACAO_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR)
);

CREATE TABLE RL_PATROCINIO_EVENTO (
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    PRIMARY KEY (ID_PARCEIRO, ID_ATIVIDADE),
    CONSTRAINT FK_PATROCINIO_PARCEIRO FOREIGN KEY (ID_PARCEIRO) REFERENCES TB_PARCEIRO(ID_PARCEIRO),
    CONSTRAINT FK_PATROCINIO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE RL_MEMBRO_PROJETO (
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_PARTICIPANTE, ID_PROJETO),
    CONSTRAINT FK_MEMBRO_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_MEMBRO_PROJETO FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);
