-- IC Extension Management - Indexing Plan
-- DBMS: PostgreSQL

-- 1. Indexing Foreign Keys for Faster Joins

CREATE INDEX IDX_PROJETO_COORDENADOR ON TB_PROJETO_EXTENSAO(ID_INSTR_COORDENADOR);
CREATE INDEX IDX_ATIVIDADE_PROJETO ON TB_ATIVIDADE(ID_PROJ_VINCULADO);
CREATE INDEX IDX_INSCRICAO_PARTICIPANTE ON RL_INSCRICAO_HISTORICO(ID_PARTICIPANTE);
CREATE INDEX IDX_INSCRICAO_ATIVIDADE ON RL_INSCRICAO_HISTORICO(ID_ATIVIDADE);
CREATE INDEX IDX_CERTIFICADO_INSCRICAO ON TB_EMISSAO_CERTIFICADO(ID_INSCRICAO);
CREATE INDEX IDX_FEEDBACK_INSCRICAO ON TB_REGISTRO_FEEDBACK(ID_INSCRICAO);

-- 2. Indexing Columns used in WHERE and GROUP BY filters

CREATE INDEX IDX_PARTICIPANTE_EMAIL ON TB_PARTICIPANTE(DS_EMAIL_CONTATO);
CREATE INDEX IDX_INSCRICAO_PRESENCA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA);
CREATE INDEX IDX_ATIVIDADE_DATA ON TB_ATIVIDADE(DT_REALIZACAO);

-- 3. Composite Indexes for specific query optimization

-- Speed up queries that filter by presence and need the grade
CREATE INDEX IDX_INSCRICAO_PRESENCA_NOTA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA, VL_NOTA_AVALIACAO);
