-- IC Extension Management - Data Integrity and Volume Verification
-- DBMS: PostgreSQL

-- 1. Volume Checks (Target: 5,000+ Participants)

SELECT 'TB_INSTRUTOR' as table_name, COUNT(*) FROM TB_INSTRUTOR
UNION ALL
SELECT 'TB_PARCEIRO', COUNT(*) FROM TB_PARCEIRO
UNION ALL
SELECT 'TB_PROJETO_EXTENSAO', COUNT(*) FROM TB_PROJETO_EXTENSAO
UNION ALL
SELECT 'TB_ATIVIDADE', COUNT(*) FROM TB_ATIVIDADE
UNION ALL
SELECT 'TB_PARTICIPANTE', COUNT(*) FROM TB_PARTICIPANTE
UNION ALL
SELECT 'RL_INSCRICAO_HISTORICO', COUNT(*) FROM RL_INSCRICAO_HISTORICO
UNION ALL
SELECT 'TB_EMISSAO_CERTIFICADO', COUNT(*) FROM TB_EMISSAO_CERTIFICADO
UNION ALL
SELECT 'TB_REGISTRO_FEEDBACK', COUNT(*) FROM TB_REGISTRO_FEEDBACK
UNION ALL
SELECT 'RL_ALOCACAO_INSTRUTOR', COUNT(*) FROM RL_ALOCACAO_INSTRUTOR
UNION ALL
SELECT 'RL_PATROCINIO_EVENTO', COUNT(*) FROM RL_PATROCINIO_EVENTO
UNION ALL
SELECT 'RL_MEMBRO_PROJETO', COUNT(*) FROM RL_MEMBRO_PROJETO;

-- 2. Consistency Checks

-- Check for orphaned activities (should have a project if not avulsa)
SELECT DS_TITULO_ATIVIDADE FROM TB_ATIVIDADE WHERE ID_PROJ_VINCULADO IS NULL;

-- Check for participants with no enrollments
SELECT DS_NOME_PARTICIPANTE FROM TB_PARTICIPANTE p
LEFT JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
WHERE i.ID_INSCRICAO IS NULL;

-- Check for activities with no instructors
SELECT DS_TITULO_ATIVIDADE FROM TB_ATIVIDADE a
LEFT JOIN RL_ALOCACAO_INSTRUTOR r ON a.ID_ATIVIDADE = r.ID_ATIVIDADE
WHERE r.ID_ATIVIDADE IS NULL;
