-- IC Extension Management Database Initialization
-- Physical Schema based on Logical Model
-- DBMS: PostgreSQL

-- 1. Base Tables (TB_)

CREATE TABLE TB_INSTRUTOR (
    ID_INSTRUTOR SERIAL PRIMARY KEY,
    DS_NOME_INSTRUTOR VARCHAR(150) NOT NULL,
    DS_ESPECIALIDADE VARCHAR(100)
);

CREATE TABLE TB_PROJETO_EXTENSAO (
    ID_PROJETO SERIAL PRIMARY KEY,
    DS_NOME_PROJETO VARCHAR(150) NOT NULL,
    DT_CRIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_INSTR_COORDENADOR INT NOT NULL,
    CONSTRAINT FK_PROJETO_COORDENADOR FOREIGN KEY (ID_INSTR_COORDENADOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR)
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL PRIMARY KEY,
    DS_TITULO_ATIVIDADE VARCHAR(150) NOT NULL,
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_PROJ_VINCULADO INT,
    CONSTRAINT FK_ATIVIDADE_PROJETO FOREIGN KEY (ID_PROJ_VINCULADO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);

CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE SERIAL PRIMARY KEY,
    DS_NOME_PARTICIPANTE VARCHAR(150) NOT NULL,
    DS_EMAIL_CONTATO VARCHAR(100) NOT NULL,
    TP_VINCULO_INST VARCHAR(30) NOT NULL
);

CREATE TABLE TB_PARCEIRO (
    ID_PARCEIRO SERIAL PRIMARY KEY,
    DS_NOME_ORGANIZACAO VARCHAR(150) NOT NULL,
    TP_PARCEIRO VARCHAR(30) NOT NULL
);

-- 2. Associative Tables (RL_)

CREATE TABLE RL_INSCRICAO_HISTORICO (
    ID_INSCRICAO SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    ST_PRESENCA VARCHAR(20) NOT NULL CHECK (ST_PRESENCA IN ('PRESENTE', 'AUSENTE')),
    VL_NOTA_AVALIACAO DECIMAL(4,2) CHECK (VL_NOTA_AVALIACAO BETWEEN 0 AND 10),
    CONSTRAINT FK_INSCRICAO_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_INSCRICAO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE TB_EMISSAO_CERTIFICADO (
    ID_CERTIFICADO SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL UNIQUE,
    DT_EMISSAO DATE NOT NULL DEFAULT CURRENT_DATE,
    CD_AUTENTICIDADE VARCHAR(60) NOT NULL UNIQUE,
    CONSTRAINT FK_CERTIFICADO_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE TB_REGISTRO_FEEDBACK (
    ID_FEEDBACK SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL UNIQUE,
    VL_NOTA_SATISFACAO INT NOT NULL CHECK (VL_NOTA_SATISFACAO BETWEEN 1 AND 5),
    DS_COMENTARIO_ABERTO TEXT,
    CONSTRAINT FK_FEEDBACK_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE RL_ALOCACAO_INSTRUTOR (
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT NOT NULL,
    PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR),
    CONSTRAINT FK_ALOCACAO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT FK_ALOCACAO_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR)
);

CREATE TABLE RL_PATROCINIO_EVENTO (
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    PRIMARY KEY (ID_PARCEIRO, ID_ATIVIDADE),
    CONSTRAINT FK_PATROCINIO_PARCEIRO FOREIGN KEY (ID_PARCEIRO) REFERENCES TB_PARCEIRO(ID_PARCEIRO),
    CONSTRAINT FK_PATROCINIO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE RL_MEMBRO_PROJETO (
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_PARTICIPANTE, ID_PROJETO),
    CONSTRAINT FK_MEMBRO_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_MEMBRO_PROJETO FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);
-- IC Extension Management - Data Population Script
-- DBMS: PostgreSQL

-- 1. Auxiliary Tables

-- TB_INSTRUTOR: 50 records
INSERT INTO TB_INSTRUTOR (DS_NOME_INSTRUTOR, DS_ESPECIALIDADE)
SELECT 'Instrutor ' || i, 'Especialidade ' || (i % 5 + 1)
FROM generate_series(1, 50) s(i);

-- TB_PARCEIRO: 20 records
INSERT INTO TB_PARCEIRO (DS_NOME_ORGANIZACAO, TP_PARCEIRO)
SELECT 'Parceiro ' || i, CASE WHEN i % 3 = 0 THEN 'ONG' WHEN i % 3 = 1 THEN 'Empresa Privada' ELSE 'Órgão Público' END
FROM generate_series(1, 20) s(i);

-- TB_PROJETO_EXTENSAO: 10 records
INSERT INTO TB_PROJETO_EXTENSAO (DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR)
SELECT 'Projeto de Extensão ' || i, CURRENT_DATE - (i || ' months')::interval, (i % 50) + 1
FROM generate_series(1, 10) s(i);

-- TB_ATIVIDADE: 100 records
INSERT INTO TB_ATIVIDADE (DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO)
SELECT 'Atividade ' || i, 'Conteúdo programático da atividade ' || i, CURRENT_DATE + (i || ' days')::interval, (i % 10) + 1
FROM generate_series(1, 100) s(i);

-- 2. Core Data (5,500 Participants)
INSERT INTO TB_PARTICIPANTE (DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST)
SELECT 
    'Participante ' || i, 
    'user' || i || '@example.com', 
    CASE WHEN i % 3 = 0 THEN 'ALUNO' WHEN i % 3 = 1 THEN 'COMUNIDADE' ELSE 'SERVIDOR' END
FROM generate_series(1, 5500) s(i);

-- 3. Relationships (11,000 Enrollments)
INSERT INTO RL_INSCRICAO_HISTORICO (ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO)
SELECT 
    p.id, 
    (random() * 99)::int + 1, 
    CASE WHEN random() > 0.2 THEN 'PRESENTE' ELSE 'AUSENTE' END,
    (random() * 10)::decimal(4,2)
FROM generate_series(1, 5500) s(i), LATERAL (SELECT i as id) p
CROSS JOIN generate_series(1, 2) g(j);

-- 4. Other Relationships

-- RL_ALOCACAO_INSTRUTOR: ~200 records
INSERT INTO RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA)
SELECT 
    a.id, 
    (random() * 49)::int + 1, 
    (random() * 10 + 2)::int
FROM generate_series(1, 100) s(i), LATERAL (SELECT i as id) a
CROSS JOIN generate_series(1, 2) g(j)
ON CONFLICT DO NOTHING;

-- RL_PATROCINIO_EVENTO: ~50 records
INSERT INTO RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE)
SELECT 
    (random() * 19)::int + 1, 
    (random() * 99)::int + 1, 
    (random() * 5000 + 500)::decimal(12,2)
FROM generate_series(1, 50) s(i)
ON CONFLICT DO NOTHING;

-- RL_MEMBRO_PROJETO: ~300 records
INSERT INTO RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO)
SELECT 
    (random() * 5499)::int + 1, 
    (random() * 9)::int + 1, 
    CASE WHEN random() > 0.5 THEN 'Bolsista' ELSE 'Voluntário' END
FROM generate_series(1, 300) s(i)
ON CONFLICT DO NOTHING;
-- IC Extension Management - Indexing Plan
-- DBMS: PostgreSQL

-- 1. Indexing Foreign Keys for Faster Joins

CREATE INDEX IDX_PROJETO_COORDENADOR ON TB_PROJETO_EXTENSAO(ID_INSTR_COORDENADOR);
CREATE INDEX IDX_ATIVIDADE_PROJETO ON TB_ATIVIDADE(ID_PROJ_VINCULADO);
CREATE INDEX IDX_INSCRICAO_PARTICIPANTE ON RL_INSCRICAO_HISTORICO(ID_PARTICIPANTE);
CREATE INDEX IDX_INSCRICAO_ATIVIDADE ON RL_INSCRICAO_HISTORICO(ID_ATIVIDADE);
CREATE INDEX IDX_CERTIFICADO_INSCRICAO ON TB_EMISSAO_CERTIFICADO(ID_INSCRICAO);
CREATE INDEX IDX_FEEDBACK_INSCRICAO ON TB_REGISTRO_FEEDBACK(ID_INSCRICAO);

-- 2. Indexing Columns used in WHERE and GROUP BY filters

CREATE INDEX IDX_PARTICIPANTE_EMAIL ON TB_PARTICIPANTE(DS_EMAIL_CONTATO);
CREATE INDEX IDX_INSCRICAO_PRESENCA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA);
CREATE INDEX IDX_ATIVIDADE_DATA ON TB_ATIVIDADE(DT_REALIZACAO);

-- 3. Composite Indexes for specific query optimization

-- Speed up queries that filter by presence and need the grade
CREATE INDEX IDX_INSCRICAO_PRESENCA_NOTA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA, VL_NOTA_AVALIACAO);
-- IC Extension Management - Intermediate Queries (10)
-- Requirements: 3+ tables, JOIN, GROUP BY, aggregation

-- 1. List all participants enrolled in activities belonging to a specific project
SELECT DISTINCT p.DS_NOME_PARTICIPANTE, proj.DS_NOME_PROJETO
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
WHERE proj.ID_PROJETO = 1;

-- 2. Count the number of activities per project
SELECT proj.DS_NOME_PROJETO, COUNT(a.ID_ATIVIDADE) as total_atividades
FROM TB_PROJETO_EXTENSAO proj
LEFT JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
GROUP BY proj.DS_NOME_PROJETO;

-- 3. List instructors and the total workload they have assigned across all activities
SELECT inst.DS_NOME_INSTRUTOR, SUM(alloc.VL_CARGA_HORARIA) as total_horas
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
GROUP BY inst.DS_NOME_INSTRUTOR;

-- 4. List partners and the total amount they have contributed to activities
SELECT part.DS_NOME_ORGANIZACAO, SUM(pat.VL_APORTE) as total_patrocinio
FROM TB_PARCEIRO part
JOIN RL_PATROCINIO_EVENTO pat ON part.ID_PARCEIRO = pat.ID_PARCEIRO
GROUP BY part.DS_NOME_ORGANIZACAO;

-- 5. List participants who have attended (ST_PRESENCA = 'PRESENTE') at least 2 activities
SELECT p.DS_NOME_PARTICIPANTE, COUNT(i.ID_ATIVIDADE) as total_presencas
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
WHERE i.ST_PRESENCA = 'PRESENTE'
GROUP BY p.DS_NOME_PARTICIPANTE
HAVING COUNT(i.ID_ATIVIDADE) >= 2;

-- 6. Calculate the average grade per activity, only for activities with more than 5 enrollments
SELECT a.DS_TITULO_ATIVIDADE, AVG(i.VL_NOTA_AVALIACAO) as media_nota
FROM TB_ATIVIDADE a
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
GROUP BY a.DS_TITULO_ATIVIDADE
HAVING COUNT(i.ID_INSCRICAO) > 5;

-- 7. List activities coordinates by projects of a specific instructor (as coordinator)
SELECT a.DS_TITULO_ATIVIDADE, proj.DS_NOME_PROJETO, inst.DS_NOME_INSTRUTOR
FROM TB_ATIVIDADE a
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
JOIN TB_INSTRUTOR inst ON proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
WHERE inst.ID_INSTRUTOR = 5;

-- 8. Count certificates issued per activity type (grouped by activity title prefix or similar, here just activity)
SELECT a.DS_TITULO_ATIVIDADE, COUNT(cert.ID_CERTIFICADO) as total_certificados
FROM TB_ATIVIDADE a
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
GROUP BY a.DS_TITULO_ATIVIDADE;

-- 9. List participants and their feedback (score and comment) for a specific activity
SELECT p.DS_NOME_PARTICIPANTE, f.VL_NOTA_SATISFACAO, f.DS_COMENTARIO_ABERTO
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
WHERE i.ID_ATIVIDADE = 10;

-- 10. List projects and the total number of members (bolsistas and voluntários)
SELECT proj.DS_NOME_PROJETO, COUNT(mem.ID_PARTICIPANTE) as total_membros
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
GROUP BY proj.DS_NOME_PROJETO;
-- IC Extension Management - Advanced Queries (20)
-- Requirements: 3+ tables, Sub-queries, Window functions, CTEs

-- 1. Rank participants by their average grade across all activities using a window function
SELECT 
    DS_NOME_PARTICIPANTE, 
    AVG(VL_NOTA_AVALIACAO) OVER(PARTITION BY p.ID_PARTICIPANTE) as media_global,
    RANK() OVER(ORDER BY AVG(VL_NOTA_AVALIACAO) DESC) as ranking
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE, i.VL_NOTA_AVALIACAO;

-- 2. Find the top 3 projects by total number of certificates issued
SELECT DS_NOME_PROJETO, total_certificados
FROM (
    SELECT proj.DS_NOME_PROJETO, COUNT(cert.ID_CERTIFICADO) as total_certificados
    FROM TB_PROJETO_EXTENSAO proj
    JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
    GROUP BY proj.DS_NOME_PROJETO
) sub
ORDER BY total_certificados DESC
LIMIT 3;

-- 3. Use a CTE to find activities with participation higher than the average participation of all activities
WITH AtividadeContagem AS (
    SELECT ID_ATIVIDADE, COUNT(*) as total_inscritos
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
)
SELECT a.DS_TITULO_ATIVIDADE, ac.total_inscritos
FROM TB_ATIVIDADE a
JOIN AtividadeContagem ac ON a.ID_ATIVIDADE = ac.ID_ATIVIDADE
WHERE ac.total_inscritos > (SELECT AVG(total_inscritos) FROM AtividadeContagem);

-- 4. List instructors who have never coordinated a project (using NOT EXISTS)
SELECT DS_NOME_INSTRUTOR
FROM TB_INSTRUTOR inst
WHERE NOT EXISTS (
    SELECT 1 FROM TB_PROJETO_EXTENSAO proj WHERE proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
);

-- 5. Calculate the running total of sponsorship contributions per partner using a window function
SELECT 
    p.DS_NOME_ORGANIZACAO, 
    pat.VL_APORTE,
    SUM(pat.VL_APORTE) OVER(PARTITION BY p.ID_PARCEIRO ORDER BY pat.ID_ATIVIDADE) as total_acumulado
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO;

-- 6. List participants and the percentage of their grade relative to the maximum grade in that activity
SELECT 
    p.DS_NOME_PARTICIPANTE, 
    a.DS_TITULO_ATIVIDADE, 
    i.VL_NOTA_AVALIACAO,
    (i.VL_NOTA_AVALIACAO / MAX(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE)) * 100 as perc_max_nota
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE;

-- 7. Find projects where the coordinator also teaches at least one activity of that project
SELECT DISTINCT proj.DS_NOME_PROJETO
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
WHERE alloc.ID_INSTRUTOR = proj.ID_INSTR_COORDENADOR;

-- 8. Count how many participants of type 'ALUNO' are in each project
SELECT proj.DS_NOME_PROJETO, COUNT(p.ID_PARTICIPANTE) as total_alunos
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
JOIN TB_PARTICIPANTE p ON mem.ID_PARTICIPANTE = p.ID_PARTICIPANTE
WHERE p.TP_VINCULO_INST = 'ALUNO'
GROUP BY proj.DS_NOME_PROJETO;

-- 9. List activities that have more than 1 instructor and also have a partner sponsor
SELECT DS_TITULO_ATIVIDADE
FROM TB_ATIVIDADE a
WHERE ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_ALOCACAO_INSTRUTOR GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 1
) AND EXISTS (
    SELECT 1 FROM RL_PATROCINIO_EVENTO pat WHERE pat.ID_ATIVIDADE = a.ID_ATIVIDADE
);

-- 10. Show the month-over-month growth of project creations (using window function)
SELECT 
    DATE_TRUNC('month', DT_CRIACAO) as mes,
    COUNT(*) as criacoes_no_mes,
    SUM(COUNT(*)) OVER(ORDER BY DATE_TRUNC('month', DT_CRIACAO)) as total_acumulado
FROM TB_PROJETO_EXTENSAO
GROUP BY mes;

-- 11. Find the activity with the highest average satisfaction rating
SELECT DS_TITULO_ATIVIDADE, media_satisfacao
FROM (
    SELECT a.DS_TITULO_ATIVIDADE, AVG(f.VL_NOTA_SATISFACAO) as media_satisfacao
    FROM TB_ATIVIDADE a
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
    GROUP BY a.DS_TITULO_ATIVIDADE
) sub
ORDER BY media_satisfacao DESC
LIMIT 1;

-- 12. List participants who have a certificate for every activity they enrolled in
SELECT DS_NOME_PARTICIPANTE
FROM TB_PARTICIPANTE p
WHERE NOT EXISTS (
    SELECT 1 FROM RL_INSCRICAO_HISTORICO i
    LEFT JOIN TB_EMISSAO_CERTIFICADO c ON i.ID_INSCRICAO = c.ID_INSCRICAO
    WHERE i.ID_PARTICIPANTE = p.ID_PARTICIPANTE AND c.ID_CERTIFICADO IS NULL
);

-- 13. Identify "super-participants" (those with more than 5 enrollments) using a subquery
SELECT DS_NOME_PARTICIPANTE, total_inscricoes
FROM (
    SELECT p.DS_NOME_PARTICIPANTE, COUNT(i.ID_INSCRICAO) as total_inscricoes
    FROM TB_PARTICIPANTE p
    JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
    GROUP BY p.DS_NOME_PARTICIPANTE
) sub
WHERE total_inscricoes > 5;

-- 14. List projects and the average workload of activities associated with them
SELECT proj.DS_NOME_PROJETO, AVG(alloc.VL_CARGA_HORARIA) as avg_workload
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
GROUP BY proj.DS_NOME_PROJETO;

-- 15. Using a window function to find the first activity date for each participant
SELECT DISTINCT
    p.DS_NOME_PARTICIPANTE,
    FIRST_VALUE(a.DT_REALIZACAO) OVER(PARTITION BY p.ID_PARTICIPANTE ORDER BY a.DT_REALIZACAO) as primeira_atividade
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE;

-- 16. Count activities by instructor specialty
SELECT inst.DS_ESPECIALIDADE, COUNT(DISTINCT alloc.ID_ATIVIDADE) as total_atividades
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
GROUP BY inst.DS_ESPECIALIDADE;

-- 17. Find the participant who gave the lowest feedback score to a highly attended activity (>20 people)
SELECT p.DS_NOME_PARTICIPANTE, f.VL_NOTA_SATISFACAO, a.DS_TITULO_ATIVIDADE
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 20
)
ORDER BY f.VL_NOTA_SATISFACAO ASC
LIMIT 1;

-- 18. List all activities that happened in the last 6 months using a CTE
WITH RecentActivities AS (
    SELECT * FROM TB_ATIVIDADE WHERE DT_REALIZACAO >= CURRENT_DATE - INTERVAL '6 months'
)
SELECT DS_TITULO_ATIVIDADE, DT_REALIZACAO FROM RecentActivities;

-- 19. Find partners who sponsor activities in more than one project
SELECT p.DS_NOME_ORGANIZACAO
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY p.DS_NOME_ORGANIZACAO
HAVING COUNT(DISTINCT a.ID_PROJ_VINCULADO) > 1;

-- 20. Calculate the difference between a participant's grade and the average grade of the activity using a window function
SELECT 
    p.DS_NOME_PARTICIPANTE, 
    a.DS_TITULO_ATIVIDADE, 
    i.VL_NOTA_AVALIACAO,
    i.VL_NOTA_AVALIACAO - AVG(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE) as diff_para_media
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE;
