-- IC Extension Management Database Initialization
-- Physical Schema based on Logical Model
-- DBMS: PostgreSQL

CREATE EXTENSION IF NOT EXISTS citext;

-- 1. Base Tables (TB_)

CREATE TABLE TB_INSTRUTOR (
    ID_INSTRUTOR SERIAL,
    DS_NOME_INSTRUTOR VARCHAR(150) NOT NULL,
    DS_ESPECIALIDADE VARCHAR(100),
    CONSTRAINT PK_TB_INSTRUTOR PRIMARY KEY (ID_INSTRUTOR)
);

CREATE TABLE TB_PROJETO_EXTENSAO (
    ID_PROJETO SERIAL,
    DS_NOME_PROJETO VARCHAR(150) NOT NULL,
    DT_CRIACAO DATE NOT NULL CONSTRAINT DF_PROJETO_CRIACAO DEFAULT CURRENT_DATE,
    ID_INSTR_COORDENADOR INT NOT NULL,
    CONSTRAINT PK_TB_PROJETO_EXTENSAO PRIMARY KEY (ID_PROJETO),
    CONSTRAINT UQ_TB_PROJETO_EXTENSAO_NOME UNIQUE (DS_NOME_PROJETO),
    CONSTRAINT FK_TB_INSTRUTOR_TB_PROJETO_EXTENSAO_COORD FOREIGN KEY (ID_INSTR_COORDENADOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR) ON DELETE RESTRICT
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL,
    DS_TITULO_ATIVIDADE VARCHAR(150) NOT NULL,
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE NOT NULL,
    ID_PROJ_VINCULADO INT,
    CONSTRAINT PK_TB_ATIVIDADE PRIMARY KEY (ID_ATIVIDADE),
    CONSTRAINT CK_TB_ATIVIDADE_DT_REALIZACAO CHECK (DT_REALIZACAO >= '2000-01-01'),
    CONSTRAINT FK_TB_PROJETO_EXTENSAO_TB_ATIVIDADE_PROJ FOREIGN KEY (ID_PROJ_VINCULADO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO) ON DELETE SET NULL
);

CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE SERIAL,
    DS_NOME_PARTICIPANTE VARCHAR(150) NOT NULL,
    DS_EMAIL_CONTATO CITEXT NOT NULL,
    TP_VINCULO_INST VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TB_PARTICIPANTE PRIMARY KEY (ID_PARTICIPANTE),
    CONSTRAINT UK_PARTICIPANTE_EMAIL UNIQUE (DS_EMAIL_CONTATO),
    CONSTRAINT CK_TB_PARTICIPANTE_EMAIL CHECK (DS_EMAIL_CONTATO LIKE '%@%'),
    CONSTRAINT CK_TB_PARTICIPANTE_VINCULO CHECK (TP_VINCULO_INST IN ('ALUNO', 'COMUNIDADE', 'SERVIDOR'))
);

CREATE TABLE TB_PARCEIRO (
    ID_PARCEIRO SERIAL,
    DS_NOME_ORGANIZACAO CITEXT NOT NULL,
    TP_PARCEIRO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TB_PARCEIRO PRIMARY KEY (ID_PARCEIRO),
    CONSTRAINT UQ_TB_PARCEIRO_NOME UNIQUE (DS_NOME_ORGANIZACAO),
    CONSTRAINT CK_TB_PARCEIRO_TIPO CHECK (TP_PARCEIRO IN ('Empresa Privada', 'ONG', 'Órgão Público'))
);

-- 2. Associative Tables (RL_)

CREATE TABLE RL_INSCRICAO_HISTORICO (
    ID_INSCRICAO SERIAL,
    ID_PARTICIPANTE INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    ST_PRESENCA VARCHAR(20) NOT NULL,
    VL_NOTA_AVALIACAO DECIMAL(4,2),
    CONSTRAINT PK_RL_INSCRICAO_HISTORICO PRIMARY KEY (ID_INSCRICAO),
    CONSTRAINT FK_TB_PARTICIPANTE_RL_INSCRICAO_HISTORICO_PART FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_TB_ATIVIDADE_RL_INSCRICAO_HISTORICO_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT CK_INSCRICAO_PRESENCA CHECK (ST_PRESENCA IN ('PRESENTE', 'AUSENTE')),
    CONSTRAINT CK_INSCRICAO_NOTA CHECK (VL_NOTA_AVALIACAO BETWEEN 0 AND 10),
    CONSTRAINT UK_INSCRICAO_UNICA UNIQUE (ID_PARTICIPANTE, ID_ATIVIDADE)
);

CREATE TABLE TB_EMISSAO_CERTIFICADO (
    ID_CERTIFICADO SERIAL,
    ID_INSCRICAO INT NOT NULL,
    DT_EMISSAO DATE NOT NULL CONSTRAINT DF_CERTIFICADO_EMISSAO DEFAULT CURRENT_DATE,
    CD_AUTENTICIDADE VARCHAR(60) NOT NULL,
    CONSTRAINT PK_TB_EMISSAO_CERTIFICADO PRIMARY KEY (ID_CERTIFICADO),
    CONSTRAINT UK_CERTIFICADO_INSCRICAO UNIQUE (ID_INSCRICAO),
    CONSTRAINT UK_CERTIFICADO_AUTENTICIDADE UNIQUE (CD_AUTENTICIDADE),
    CONSTRAINT FK_RL_INSCRICAO_HISTORICO_TB_EMISSAO_CERTIFICADO_INSC FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE TB_REGISTRO_FEEDBACK (
    ID_FEEDBACK SERIAL,
    ID_INSCRICAO INT NOT NULL,
    VL_NOTA_SATISFACAO INT NOT NULL,
    DS_COMENTARIO_ABERTO TEXT,
    CONSTRAINT PK_TB_REGISTRO_FEEDBACK PRIMARY KEY (ID_FEEDBACK),
    CONSTRAINT UK_FEEDBACK_INSCRICAO UNIQUE (ID_INSCRICAO),
    CONSTRAINT CK_FEEDBACK_SATISFACAO CHECK (VL_NOTA_SATISFACAO BETWEEN 1 AND 5),
    CONSTRAINT FK_RL_INSCRICAO_HISTORICO_TB_REGISTRO_FEEDBACK_INSC FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE RL_ALOCACAO_INSTRUTOR (
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT NOT NULL,
    CONSTRAINT PK_RL_ALOCACAO_INSTRUTOR PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR),
    CONSTRAINT FK_TB_ATIVIDADE_RL_ALOCACAO_INSTRUTOR_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT FK_TB_INSTRUTOR_RL_ALOCACAO_INSTRUTOR_INST FOREIGN KEY (ID_INSTRUTOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR),
    CONSTRAINT CK_ALOCACAO_CARGA CHECK (VL_CARGA_HORARIA > 0)
);

CREATE TABLE RL_PATROCINIO_EVENTO (
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    CONSTRAINT PK_RL_PATROCINIO_EVENTO PRIMARY KEY (ID_PARCEIRO, ID_ATIVIDADE),
    CONSTRAINT FK_TB_PARCEIRO_RL_PATROCINIO_EVENTO_PARC FOREIGN KEY (ID_PARCEIRO) REFERENCES TB_PARCEIRO(ID_PARCEIRO),
    CONSTRAINT FK_TB_ATIVIDADE_RL_PATROCINIO_EVENTO_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT CK_PATROCINIO_APORTE CHECK (VL_APORTE > 0)
);

CREATE TABLE RL_MEMBRO_PROJETO (
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_RL_MEMBRO_PROJETO PRIMARY KEY (ID_PARTICIPANTE, ID_PROJETO),
    CONSTRAINT FK_TB_PARTICIPANTE_RL_MEMBRO_PROJETO_PART FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_TB_PROJETO_EXTENSAO_RL_MEMBRO_PROJETO_PROJ FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);

-- IC Extension Management - Rename Implicit Sequences to SQ_ Naming
-- Compliant with MAD1: SQ_ prefix for sequences

ALTER SEQUENCE tb_instrutor_id_instrutor_seq RENAME TO SQ_INSTRUTOR;
ALTER SEQUENCE tb_projeto_extensao_id_projeto_seq RENAME TO SQ_PROJETO_EXTENSAO;
ALTER SEQUENCE tb_atividade_id_atividade_seq RENAME TO SQ_ATIVIDADE;
ALTER SEQUENCE tb_participante_id_participante_seq RENAME TO SQ_PARTICIPANTE;
ALTER SEQUENCE tb_parceiro_id_parceiro_seq RENAME TO SQ_PARCEIRO;
ALTER SEQUENCE rl_inscricao_historico_id_inscricao_seq RENAME TO SQ_INSCRICAO_HISTORICO;
ALTER SEQUENCE tb_emissao_certificado_id_certificado_seq RENAME TO SQ_EMISSAO_CERTIFICADO;
ALTER SEQUENCE tb_registro_feedback_id_feedback_seq RENAME TO SQ_REGISTRO_FEEDBACK;

-- IC Extension Management Database - Audit Triggers
-- Compliant with MAD1 Rules
-- DBMS: PostgreSQL

-- 1. Create Audit Tables (TA_)

CREATE TABLE TA_TB_ATIVIDADE (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_ATIVIDADE INT NOT NULL,
    DS_TITULO_ATIVIDADE VARCHAR(150),
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE,
    ID_PROJ_VINCULADO INT,
    TP_OPERACAO CHAR(1) NOT NULL, -- I/U/D
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_INSCRICAO_HISTORICO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL,
    ID_PARTICIPANTE INT,
    ID_ATIVIDADE INT,
    ST_PRESENCA VARCHAR(20),
    VL_NOTA_AVALIACAO DECIMAL(4,2),
    TP_OPERACAO CHAR(1) NOT NULL, -- I/U/D
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

-- 2. Create Audit Functions

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_ATIVIDADE()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_ATIVIDADE, OLD.DS_TITULO_ATIVIDADE, OLD.DS_CONTEUDO_PROG, OLD.DT_REALIZACAO, OLD.ID_PROJ_VINCULADO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.DS_TITULO_ATIVIDADE, NEW.DS_CONTEUDO_PROG, NEW.DT_REALIZACAO, NEW.ID_PROJ_VINCULADO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_ATIVIDADE (ID_ATIVIDADE, DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.DS_TITULO_ATIVIDADE, NEW.DS_CONTEUDO_PROG, NEW.DT_REALIZACAO, NEW.ID_PROJ_VINCULADO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_INSCR_HIST()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_INSCRICAO, OLD.ID_PARTICIPANTE, OLD.ID_ATIVIDADE, OLD.ST_PRESENCA, OLD.VL_NOTA_AVALIACAO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSCRICAO, NEW.ID_PARTICIPANTE, NEW.ID_ATIVIDADE, NEW.ST_PRESENCA, NEW.VL_NOTA_AVALIACAO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_INSCRICAO_HISTORICO (ID_INSCRICAO, ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSCRICAO, NEW.ID_PARTICIPANTE, NEW.ID_ATIVIDADE, NEW.ST_PRESENCA, NEW.VL_NOTA_AVALIACAO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 3. Create Triggers (TG_A_[I/U/D]_)

CREATE TRIGGER TG_A_I_TB_ATIVIDADE
AFTER INSERT ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_U_TB_ATIVIDADE
AFTER UPDATE ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_D_TB_ATIVIDADE
AFTER DELETE ON TB_ATIVIDADE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_ATIVIDADE();

CREATE TRIGGER TG_A_I_RL_INSCRICAO
AFTER INSERT ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_INSCR_HIST();

CREATE TRIGGER TG_A_U_RL_INSCRICAO
AFTER UPDATE ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_INSCR_HIST();

CREATE TRIGGER TG_A_D_RL_INSCRICAO
AFTER DELETE ON RL_INSCRICAO_HISTORICO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_INSCR_HIST();

-- Audit Table for PII-sensitive data (PPP1 compliance)
CREATE TABLE TA_TB_PARTICIPANTE (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    DS_NOME_PARTICIPANTE VARCHAR(150),
    DS_EMAIL_CONTATO VARCHAR(100),
    TP_VINCULO_INST VARCHAR(30),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_PARTICIPANTE()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_PARTICIPANTE (ID_PARTICIPANTE, DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARTICIPANTE, OLD.DS_NOME_PARTICIPANTE, OLD.DS_EMAIL_CONTATO, OLD.TP_VINCULO_INST, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_PARTICIPANTE (ID_PARTICIPANTE, DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.DS_NOME_PARTICIPANTE, NEW.DS_EMAIL_CONTATO, NEW.TP_VINCULO_INST, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_PARTICIPANTE (ID_PARTICIPANTE, DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.DS_NOME_PARTICIPANTE, NEW.DS_EMAIL_CONTATO, NEW.TP_VINCULO_INST, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TG_A_I_TB_PARTICIPANTE
AFTER INSERT ON TB_PARTICIPANTE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARTICIPANTE();

CREATE TRIGGER TG_A_U_TB_PARTICIPANTE
AFTER UPDATE ON TB_PARTICIPANTE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARTICIPANTE();

CREATE TRIGGER TG_A_D_TB_PARTICIPANTE
AFTER DELETE ON TB_PARTICIPANTE
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARTICIPANTE();

-- ============================================================
-- Audit Tables for remaining tables
-- ============================================================

CREATE TABLE TA_TB_PROJETO_EXTENSAO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PROJETO INT NOT NULL,
    DS_NOME_PROJETO VARCHAR(150),
    DT_CRIACAO DATE,
    ID_INSTR_COORDENADOR INT,
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_INSTRUTOR (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_INSTRUTOR INT NOT NULL,
    DS_NOME_INSTRUTOR VARCHAR(150),
    DS_ESPECIALIDADE VARCHAR(100),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_PARCEIRO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARCEIRO INT NOT NULL,
    DS_NOME_ORGANIZACAO VARCHAR(150),
    TP_PARCEIRO VARCHAR(30),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_EMISSAO_CERTIFICADO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_CERTIFICADO INT NOT NULL,
    ID_INSCRICAO INT,
    DT_EMISSAO DATE,
    CD_AUTENTICIDADE VARCHAR(60),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_TB_REGISTRO_FEEDBACK (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_FEEDBACK INT NOT NULL,
    ID_INSCRICAO INT,
    VL_NOTA_SATISFACAO INT,
    DS_COMENTARIO_ABERTO TEXT,
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_ALOCACAO_INSTRUTOR (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT,
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_PATROCINIO_EVENTO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

CREATE TABLE TA_RL_MEMBRO_PROJETO (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30),
    TP_OPERACAO CHAR(1) NOT NULL,
    DT_OPERACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NM_USUARIO_BD VARCHAR(100) NOT NULL,
    NM_USUARIO_APLICACAO VARCHAR(100),
    NM_TERMINAL VARCHAR(100)
);

-- ============================================================
-- Audit Functions for remaining tables
-- ============================================================

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_PROJETO_EXTENSAO (ID_PROJETO, DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PROJETO, OLD.DS_NOME_PROJETO, OLD.DT_CRIACAO, OLD.ID_INSTR_COORDENADOR, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_PROJETO_EXTENSAO (ID_PROJETO, DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PROJETO, NEW.DS_NOME_PROJETO, NEW.DT_CRIACAO, NEW.ID_INSTR_COORDENADOR, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_PROJETO_EXTENSAO (ID_PROJETO, DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PROJETO, NEW.DS_NOME_PROJETO, NEW.DT_CRIACAO, NEW.ID_INSTR_COORDENADOR, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_INSTRUTOR()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_INSTRUTOR (ID_INSTRUTOR, DS_NOME_INSTRUTOR, DS_ESPECIALIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_INSTRUTOR, OLD.DS_NOME_INSTRUTOR, OLD.DS_ESPECIALIDADE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_INSTRUTOR (ID_INSTRUTOR, DS_NOME_INSTRUTOR, DS_ESPECIALIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSTRUTOR, NEW.DS_NOME_INSTRUTOR, NEW.DS_ESPECIALIDADE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_INSTRUTOR (ID_INSTRUTOR, DS_NOME_INSTRUTOR, DS_ESPECIALIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_INSTRUTOR, NEW.DS_NOME_INSTRUTOR, NEW.DS_ESPECIALIDADE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_PARCEIRO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_PARCEIRO (ID_PARCEIRO, DS_NOME_ORGANIZACAO, TP_PARCEIRO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARCEIRO, OLD.DS_NOME_ORGANIZACAO, OLD.TP_PARCEIRO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_PARCEIRO (ID_PARCEIRO, DS_NOME_ORGANIZACAO, TP_PARCEIRO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.DS_NOME_ORGANIZACAO, NEW.TP_PARCEIRO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_PARCEIRO (ID_PARCEIRO, DS_NOME_ORGANIZACAO, TP_PARCEIRO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.DS_NOME_ORGANIZACAO, NEW.TP_PARCEIRO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_EMISSAO_CERTIFICADO (ID_CERTIFICADO, ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_CERTIFICADO, OLD.ID_INSCRICAO, OLD.DT_EMISSAO, OLD.CD_AUTENTICIDADE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_EMISSAO_CERTIFICADO (ID_CERTIFICADO, ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_CERTIFICADO, NEW.ID_INSCRICAO, NEW.DT_EMISSAO, NEW.CD_AUTENTICIDADE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_EMISSAO_CERTIFICADO (ID_CERTIFICADO, ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_CERTIFICADO, NEW.ID_INSCRICAO, NEW.DT_EMISSAO, NEW.CD_AUTENTICIDADE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_TB_REGISTRO_FEEDBACK (ID_FEEDBACK, ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_FEEDBACK, OLD.ID_INSCRICAO, OLD.VL_NOTA_SATISFACAO, OLD.DS_COMENTARIO_ABERTO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_TB_REGISTRO_FEEDBACK (ID_FEEDBACK, ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_FEEDBACK, NEW.ID_INSCRICAO, NEW.VL_NOTA_SATISFACAO, NEW.DS_COMENTARIO_ABERTO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_TB_REGISTRO_FEEDBACK (ID_FEEDBACK, ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_FEEDBACK, NEW.ID_INSCRICAO, NEW.VL_NOTA_SATISFACAO, NEW.DS_COMENTARIO_ABERTO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_ATIVIDADE, OLD.ID_INSTRUTOR, OLD.VL_CARGA_HORARIA, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.ID_INSTRUTOR, NEW.VL_CARGA_HORARIA, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_ATIVIDADE, NEW.ID_INSTRUTOR, NEW.VL_CARGA_HORARIA, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARCEIRO, OLD.ID_ATIVIDADE, OLD.VL_APORTE, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.ID_ATIVIDADE, NEW.VL_APORTE, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARCEIRO, NEW.ID_ATIVIDADE, NEW.VL_APORTE, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO()
RETURNS TRIGGER AS $$
DECLARE
    v_app_user VARCHAR(100);
BEGIN
    v_app_user := COALESCE(nullif(current_setting('app.usuario', true), ''), current_user);
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO TA_RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (OLD.ID_PARTICIPANTE, OLD.ID_PROJETO, OLD.TP_PAPEL_ATUACAO, 'D', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO TA_RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.ID_PROJETO, NEW.TP_PAPEL_ATUACAO, 'U', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO TA_RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO, TP_OPERACAO, NM_USUARIO_BD, NM_USUARIO_APLICACAO, NM_TERMINAL)
        VALUES (NEW.ID_PARTICIPANTE, NEW.ID_PROJETO, NEW.TP_PAPEL_ATUACAO, 'I', current_user, v_app_user, inet_client_addr()::varchar);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Triggers for remaining tables
-- ============================================================

CREATE TRIGGER TG_A_I_TB_PROJETO_EXTENSAO
AFTER INSERT ON TB_PROJETO_EXTENSAO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO();

CREATE TRIGGER TG_A_U_TB_PROJETO_EXTENSAO
AFTER UPDATE ON TB_PROJETO_EXTENSAO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO();

CREATE TRIGGER TG_A_D_TB_PROJETO_EXTENSAO
AFTER DELETE ON TB_PROJETO_EXTENSAO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PROJETO_EXTENSAO();

CREATE TRIGGER TG_A_I_TB_INSTRUTOR
AFTER INSERT ON TB_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_INSTRUTOR();

CREATE TRIGGER TG_A_U_TB_INSTRUTOR
AFTER UPDATE ON TB_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_INSTRUTOR();

CREATE TRIGGER TG_A_D_TB_INSTRUTOR
AFTER DELETE ON TB_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_INSTRUTOR();

CREATE TRIGGER TG_A_I_TB_PARCEIRO
AFTER INSERT ON TB_PARCEIRO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARCEIRO();

CREATE TRIGGER TG_A_U_TB_PARCEIRO
AFTER UPDATE ON TB_PARCEIRO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARCEIRO();

CREATE TRIGGER TG_A_D_TB_PARCEIRO
AFTER DELETE ON TB_PARCEIRO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_PARCEIRO();

CREATE TRIGGER TG_A_I_TB_EMISSAO_CERTIFICADO
AFTER INSERT ON TB_EMISSAO_CERTIFICADO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO();

CREATE TRIGGER TG_A_U_TB_EMISSAO_CERTIFICADO
AFTER UPDATE ON TB_EMISSAO_CERTIFICADO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO();

CREATE TRIGGER TG_A_D_TB_EMISSAO_CERTIFICADO
AFTER DELETE ON TB_EMISSAO_CERTIFICADO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_EMISSAO_CERTIFICADO();

CREATE TRIGGER TG_A_I_TB_REGISTRO_FEEDBACK
AFTER INSERT ON TB_REGISTRO_FEEDBACK
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK();

CREATE TRIGGER TG_A_U_TB_REGISTRO_FEEDBACK
AFTER UPDATE ON TB_REGISTRO_FEEDBACK
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK();

CREATE TRIGGER TG_A_D_TB_REGISTRO_FEEDBACK
AFTER DELETE ON TB_REGISTRO_FEEDBACK
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_TB_REGISTRO_FEEDBACK();

CREATE TRIGGER TG_A_I_RL_ALOCACAO_INSTRUTOR
AFTER INSERT ON RL_ALOCACAO_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR();

CREATE TRIGGER TG_A_U_RL_ALOCACAO_INSTRUTOR
AFTER UPDATE ON RL_ALOCACAO_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR();

CREATE TRIGGER TG_A_D_RL_ALOCACAO_INSTRUTOR
AFTER DELETE ON RL_ALOCACAO_INSTRUTOR
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_ALOCACAO_INSTRUTOR();

CREATE TRIGGER TG_A_I_RL_PATROCINIO_EVENTO
AFTER INSERT ON RL_PATROCINIO_EVENTO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO();

CREATE TRIGGER TG_A_U_RL_PATROCINIO_EVENTO
AFTER UPDATE ON RL_PATROCINIO_EVENTO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO();

CREATE TRIGGER TG_A_D_RL_PATROCINIO_EVENTO
AFTER DELETE ON RL_PATROCINIO_EVENTO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_PATROCINIO_EVENTO();

CREATE TRIGGER TG_A_I_RL_MEMBRO_PROJETO
AFTER INSERT ON RL_MEMBRO_PROJETO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO();

CREATE TRIGGER TG_A_U_RL_MEMBRO_PROJETO
AFTER UPDATE ON RL_MEMBRO_PROJETO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO();

CREATE TRIGGER TG_A_D_RL_MEMBRO_PROJETO
AFTER DELETE ON RL_MEMBRO_PROJETO
FOR EACH ROW EXECUTE FUNCTION FC_AUDIT_RL_MEMBRO_PROJETO();

-- IC Extension Management Database - Roles and Permissions
-- Compliant with PPP1 Rules
-- DBMS: PostgreSQL

-- 1. Create Roles

-- DBA Role (Admin)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'dba_ic') THEN
    CREATE ROLE dba_ic WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'admin_password';
  END IF;
END $$;

-- Sistema Role (Application)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'sistema_ic') THEN
    CREATE ROLE sistema_ic WITH LOGIN PASSWORD 'sys_password';
  END IF;
END $$;

-- Análise Role (Data Analyst)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'analise_ic') THEN
    CREATE ROLE analise_ic WITH LOGIN PASSWORD 'analyst_password';
  END IF;
END $$;

-- Backup Role (Backup Operator)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'dbbackup_ic') THEN
    CREATE ROLE dbbackup_ic WITH LOGIN PASSWORD 'backup_password';
  END IF;
END $$;

-- 2. Grant Permissions

-- Permissions for Sistema (DML only on business tables)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sistema_ic;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sistema_ic;
-- Explicitly revoke access from audit tables to avoid spoofing
REVOKE ALL PRIVILEGES ON TA_TB_ATIVIDADE FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_RL_INSCRICAO_HISTORICO FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_TB_PARTICIPANTE FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_TB_PROJETO_EXTENSAO FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_TB_INSTRUTOR FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_TB_PARCEIRO FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_TB_EMISSAO_CERTIFICADO FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_TB_REGISTRO_FEEDBACK FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_RL_ALOCACAO_INSTRUTOR FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_RL_PATROCINIO_EVENTO FROM sistema_ic;
REVOKE ALL PRIVILEGES ON TA_RL_MEMBRO_PROJETO FROM sistema_ic;

-- Permissions for Análise (SELECT only)
GRANT SELECT ON ALL TABLES IN SCHEMA public TO analise_ic;
-- Analysts can read audit tables if needed, but not modify them
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM analise_ic;

-- Permissions for Backup
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbbackup_ic;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO dbbackup_ic;
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM dbbackup_ic;

-- Restrict audit table access (MAD1 §7: only AD and DBA teams)


-- Set default privileges for future tables (Commented out for security)
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sistema_ic;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO analise_ic;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dbbackup_ic;
-- NOTE: If uncommented, these defaults will automatically grant privileges to future audit tables in public schema.

-- IC Extension Management - Data Population Script
-- DBMS: PostgreSQL

-- 1. Auxiliary Tables

-- TB_INSTRUTOR: 50 records
INSERT INTO TB_INSTRUTOR (DS_NOME_INSTRUTOR, DS_ESPECIALIDADE)
SELECT 'Instrutor ' || i, 'Especialidade ' || (i % 5 + 1)
FROM generate_series(1, 50) s(i);

-- TB_PARCEIRO: 20 records
INSERT INTO TB_PARCEIRO (DS_NOME_ORGANIZACAO, TP_PARCEIRO)
SELECT 'Parceiro ' || i, CASE WHEN i % 3 = 0 THEN 'ONG' WHEN i % 3 = 1 THEN 'Empresa Privada' ELSE 'Órgão Público' END
FROM generate_series(1, 20) s(i);

-- TB_PROJETO_EXTENSAO: 10 records
INSERT INTO TB_PROJETO_EXTENSAO (DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR)
SELECT 'Projeto de Extensão ' || i, CURRENT_DATE - (i || ' months')::interval, (i % 50) + 1
FROM generate_series(1, 10) s(i);

-- TB_ATIVIDADE: 100 records (80 past/current + 20 future for realistic queries)
INSERT INTO TB_ATIVIDADE (DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO)
SELECT 'Atividade ' || i, 'Conteúdo programático da atividade ' || i, CURRENT_DATE - ((80 - i) || ' days')::interval, (i % 10) + 1
FROM generate_series(1, 100) s(i);

-- 2. Core Data (5,500 Participants)
INSERT INTO TB_PARTICIPANTE (DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST)
SELECT 
    'Participante ' || i, 
    'user' || i || '@example.com', 
    CASE WHEN i % 3 = 0 THEN 'ALUNO' WHEN i % 3 = 1 THEN 'COMUNIDADE' ELSE 'SERVIDOR' END
FROM generate_series(1, 5500) s(i);

-- 3. Relationships (11,000 Enrollments)
INSERT INTO RL_INSCRICAO_HISTORICO (ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO)
SELECT 
    p.id, 
    (random() * 99)::int + 1, 
    CASE WHEN random() > 0.2 THEN 'PRESENTE' ELSE 'AUSENTE' END,
    (random() * 10)::decimal(4,2)
FROM generate_series(1, 5500) s(i), LATERAL (SELECT i AS ID) p
CROSS JOIN generate_series(1, 2) g(j)
ON CONFLICT DO NOTHING;

-- Insert additional enrollments for "super-participants" (>5 enrollments)
INSERT INTO RL_INSCRICAO_HISTORICO (ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO)
SELECT 
    p.id, 
    (random() * 99)::int + 1, 
    'PRESENTE',
    (random() * 10)::decimal(4,2)
FROM generate_series(1, 50) s(i), LATERAL (SELECT i AS ID) p
CROSS JOIN generate_series(1, 6) g(j)
ON CONFLICT DO NOTHING;

-- 4. Other Relationships

-- RL_ALOCACAO_INSTRUTOR: ~200 records
INSERT INTO RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA)
SELECT 
    a.id, 
    (random() * 49)::int + 1, 
    (random() * 10 + 2)::int
FROM generate_series(1, 100) s(i), LATERAL (SELECT i AS ID) a
CROSS JOIN generate_series(1, 2) g(j)
ON CONFLICT DO NOTHING;

-- RL_PATROCINIO_EVENTO: ~50 records
INSERT INTO RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE)
SELECT 
    (random() * 19)::int + 1, 
    (random() * 99)::int + 1, 
    (random() * 5000 + 500)::decimal(12,2)
FROM generate_series(1, 50) s(i)
ON CONFLICT DO NOTHING;

-- RL_MEMBRO_PROJETO: ~300 records
INSERT INTO RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO)
SELECT 
    (random() * 5499)::int + 1, 
    (random() * 9)::int + 1, 
    CASE WHEN random() > 0.5 THEN 'Bolsista' ELSE 'Voluntário' END
FROM generate_series(1, 300) s(i)
ON CONFLICT DO NOTHING;

-- TB_EMISSAO_CERTIFICADO: one per PRESENTE enrollment (~8,800 records)
INSERT INTO TB_EMISSAO_CERTIFICADO (ID_INSCRICAO, DT_EMISSAO, CD_AUTENTICIDADE)
SELECT 
    i.ID_INSCRICAO,
    a.DT_REALIZACAO + INTERVAL '1 day',
    'AUTH-' || UPPER(SUBSTR(MD5(random()::text || i.ID_INSCRICAO::text), 1, 12))
FROM RL_INSCRICAO_HISTORICO i
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE i.ST_PRESENCA = 'PRESENTE'
ON CONFLICT DO NOTHING;

-- TB_REGISTRO_FEEDBACK: one per PRESENTE enrollment (~8,800 records)
INSERT INTO TB_REGISTRO_FEEDBACK (ID_INSCRICAO, VL_NOTA_SATISFACAO, DS_COMENTARIO_ABERTO)
SELECT 
    i.ID_INSCRICAO,
    (random() * 4 + 1)::int,
    CASE 
        WHEN random() < 0.3 THEN 'Excelente atividade!'
        WHEN random() < 0.6 THEN 'Muito bom, recomendo.'
        WHEN random() < 0.8 THEN 'Atividade razoável, poderia melhorar.'
        ELSE NULL
    END
FROM RL_INSCRICAO_HISTORICO i
WHERE i.ST_PRESENCA = 'PRESENTE'
ON CONFLICT DO NOTHING;

-- IC Extension Management - Indexing Plan
-- DBMS: PostgreSQL

-- 1. Indexing Foreign Keys for Faster Joins

CREATE INDEX IDX_PROJETO_COORDENADOR ON TB_PROJETO_EXTENSAO(ID_INSTR_COORDENADOR);
CREATE INDEX IDX_ATIVIDADE_PROJETO ON TB_ATIVIDADE(ID_PROJ_VINCULADO);
CREATE INDEX IDX_INSCRICAO_PARTICIPANTE ON RL_INSCRICAO_HISTORICO(ID_PARTICIPANTE);
CREATE INDEX IDX_INSCRICAO_ATIVIDADE ON RL_INSCRICAO_HISTORICO(ID_ATIVIDADE);
-- Índices redundantes removidos (ID_INSCRICAO já possui índice automático pela constraint UNIQUE)
-- CREATE INDEX IDX_CERTIFICADO_INSCRICAO ON TB_EMISSAO_CERTIFICADO(ID_INSCRICAO);
-- CREATE INDEX IDX_FEEDBACK_INSCRICAO ON TB_REGISTRO_FEEDBACK(ID_INSCRICAO);

-- 2. Indexing Columns used in WHERE and GROUP BY filters

-- Índices redundantes removidos (DS_EMAIL_CONTATO já possui índice automático pela constraint UNIQUE)
-- CREATE INDEX IDX_PARTICIPANTE_EMAIL ON TB_PARTICIPANTE(DS_EMAIL_CONTATO);
CREATE INDEX IDX_INSCRICAO_PRESENCA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA);
CREATE INDEX IDX_ATIVIDADE_DATA ON TB_ATIVIDADE(DT_REALIZACAO);

-- 3. Composite Indexes for specific query optimization

-- Speed up queries that filter by presence and need the grade
CREATE INDEX IDX_INSCRICAO_PRESENCA_NOTA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA, VL_NOTA_AVALIACAO);

-- IC Extension Management - Intermediate Queries (10)
-- Requirements: RF1-RF7 (Activity management, enrollment, certificates, feedback, partnerships, grades, projects)
-- Criteria: ≥3 distinct base tables, ≥2 of: JOIN, GROUP BY, WINDOW functions, COUNT

-- [RF2] Query 1: Count enrollments per participant in activities of project 1
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE, TB_PROJETO_EXTENSAO
-- Funções: JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE,
       proj.DS_NOME_PROJETO,
       COUNT(i.ID_INSCRICAO) AS TOTAL_INSCRICOES
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
WHERE proj.ID_PROJETO = 1
GROUP BY p.DS_NOME_PARTICIPANTE, proj.DS_NOME_PROJETO;

-- [RF1] Query 2: Count the number of activities per project with coordinator name
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, TB_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT
SELECT proj.DS_NOME_PROJETO,
       inst.DS_NOME_INSTRUTOR AS COORDENADOR,
       COUNT(a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES
FROM TB_PROJETO_EXTENSAO proj
LEFT JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN TB_INSTRUTOR inst ON proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
GROUP BY proj.DS_NOME_PROJETO, inst.DS_NOME_INSTRUTOR;

-- [RF1] Query 3: List instructors and total workload with activity context
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, SUM, COUNT
SELECT inst.DS_NOME_INSTRUTOR,
       COUNT(a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES,
       SUM(alloc.VL_CARGA_HORARIA) AS TOTAL_HORAS
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY inst.DS_NOME_INSTRUTOR;

-- [RF5] Query 4: List partners, total contributions, and sponsored activities
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, SUM, COUNT
SELECT part.DS_NOME_ORGANIZACAO,
       COUNT(a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES_PATROCINADAS,
       SUM(pat.VL_APORTE) AS TOTAL_PATROCINIO
FROM TB_PARCEIRO part
JOIN RL_PATROCINIO_EVENTO pat ON part.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY part.DS_NOME_ORGANIZACAO;

-- [RF2] Query 5: Participants attending ≥2 activities, showing activity names
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT, HAVING
SELECT p.DS_NOME_PARTICIPANTE,
       COUNT(a.ID_ATIVIDADE) AS TOTAL_PRESENCAS,
       STRING_AGG(a.DS_TITULO_ATIVIDADE, ', ') AS NOMES_ATIVIDADES
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE i.ST_PRESENCA = 'PRESENTE'
GROUP BY p.DS_NOME_PARTICIPANTE
HAVING COUNT(a.ID_ATIVIDADE) >= 2;

-- [RF6] Query 6: Average grade per activity with project context
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PROJETO_EXTENSAO
-- Funções: JOIN, GROUP BY, AVG, COUNT
SELECT a.DS_TITULO_ATIVIDADE,
       proj.DS_NOME_PROJETO,
       AVG(i.VL_NOTA_AVALIACAO) AS MEDIA_NOTA,
       COUNT(i.ID_INSCRICAO) AS TOTAL_INSCRICOES
FROM TB_ATIVIDADE a
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
GROUP BY a.DS_TITULO_ATIVIDADE, proj.DS_NOME_PROJETO
HAVING COUNT(i.ID_INSCRICAO) > 5;

-- [RF7] Query 7: Count activities coordinated per instructor
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_ATIVIDADE, TB_PROJETO_EXTENSAO, TB_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT
SELECT inst.DS_NOME_INSTRUTOR,
       COUNT(a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES_COORDENADAS
FROM TB_ATIVIDADE a
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
JOIN TB_INSTRUTOR inst ON proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
GROUP BY inst.DS_NOME_INSTRUTOR;

-- [RF3] Query 8: Count certificates issued per activity
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: JOIN, GROUP BY, COUNT
SELECT a.DS_TITULO_ATIVIDADE, COUNT(cert.ID_CERTIFICADO) AS TOTAL_CERTIFICADOS
FROM TB_ATIVIDADE a
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
GROUP BY a.DS_TITULO_ATIVIDADE;

-- [RF4] Query 9: Count feedbacks and average satisfaction per participant
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK
-- Funções: JOIN, GROUP BY, COUNT, AVG
SELECT p.DS_NOME_PARTICIPANTE,
       COUNT(f.ID_FEEDBACK) AS TOTAL_FEEDBACKS,
       AVG(f.VL_NOTA_SATISFACAO) AS MEDIA_SATISFACAO
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
GROUP BY p.DS_NOME_PARTICIPANTE;

-- [RF7] Query 10: List projects and total members with participant names
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, RL_MEMBRO_PROJETO, TB_PARTICIPANTE
-- Funções: JOIN, GROUP BY, COUNT
SELECT proj.DS_NOME_PROJETO,
       COUNT(mem.ID_PARTICIPANTE) AS TOTAL_MEMBROS,
       STRING_AGG(p.DS_NOME_PARTICIPANTE, ', ') AS NOMES_PARTICIPANTES
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
JOIN TB_PARTICIPANTE p ON mem.ID_PARTICIPANTE = p.ID_PARTICIPANTE
GROUP BY proj.DS_NOME_PROJETO;

-- IC Extension Management - Advanced Queries (20)
-- Requirements: 3+ tables, 3+ of: Sub-queries, JOIN, GROUP BY, Window functions, COUNT

-- [RF6] Query 1: Rank participants by average grade across all activities
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, WINDOW (RANK)
SELECT
    sub.DS_NOME_PARTICIPANTE,
    sub.media_global,
    RANK() OVER(ORDER BY sub.media_global DESC) AS RANKING
FROM (
    SELECT
        p.ID_PARTICIPANTE,
        p.DS_NOME_PARTICIPANTE,
        AVG(i.VL_NOTA_AVALIACAO) AS MEDIA_GLOBAL
    FROM TB_PARTICIPANTE p
    JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
    JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
    GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE
) sub;

-- [RF3] Query 2: Find the top 3 projects by total number of certificates issued
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
SELECT DS_NOME_PROJETO, total_certificados
FROM (
    SELECT proj.DS_NOME_PROJETO, COUNT(cert.ID_CERTIFICADO) AS TOTAL_CERTIFICADOS
    FROM TB_PROJETO_EXTENSAO proj
    JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
    GROUP BY proj.DS_NOME_PROJETO
) sub
ORDER BY total_certificados DESC
LIMIT 3;

-- [RF2] Query 3: Activities with participation higher than the average, showing project name
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PROJETO_EXTENSAO
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
WITH AtividadeContagem AS (
    SELECT ID_ATIVIDADE, COUNT(*) AS TOTAL_INSCRITOS
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
)
SELECT a.DS_TITULO_ATIVIDADE, proj.DS_NOME_PROJETO, ac.total_inscritos
FROM TB_ATIVIDADE a
JOIN AtividadeContagem ac ON a.ID_ATIVIDADE = ac.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
WHERE ac.total_inscritos > (SELECT AVG(total_inscritos) FROM AtividadeContagem);

-- [RF7] Query 4: Instructors who never coordinated a project but are allocated to activities
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE, TB_PROJETO_EXTENSAO
-- Funções: SUB-QUERY (NOT EXISTS), JOIN, GROUP BY, COUNT
SELECT
    inst.DS_NOME_INSTRUTOR,
    COUNT(DISTINCT alloc.ID_ATIVIDADE) AS TOTAL_ATIVIDADES_ALOCADAS
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE NOT EXISTS (
    SELECT 1 FROM TB_PROJETO_EXTENSAO proj
    WHERE proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
)
GROUP BY inst.ID_INSTRUTOR, inst.DS_NOME_INSTRUTOR;

-- [RF5] Query 5: Running total of sponsorship contributions per partner with activity names
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (SUM), COUNT
SELECT
    p.DS_NOME_ORGANIZACAO,
    a.DS_TITULO_ATIVIDADE,
    pat.VL_APORTE,
    SUM(pat.VL_APORTE) OVER(PARTITION BY p.ID_PARCEIRO ORDER BY a.ID_ATIVIDADE) AS TOTAL_ACUMULADO,
    COUNT(*) OVER(PARTITION BY p.ID_PARCEIRO) AS TOTAL_PATROCINIOS_PARCEIRO
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE;

-- [RF6] Query 6: Participant grade AS PERCENTAGE of max grade, only for activities with >5 enrollments
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW, SUB-QUERY
SELECT
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    i.VL_NOTA_AVALIACAO,
    (i.VL_NOTA_AVALIACAO / NULLIF(MAX(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE), 0)) * 100 AS PERC_MAX_NOTA
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
    HAVING COUNT(*) > 5
);

-- [RF7] Query 7: Projects where the coordinator also teaches, only projects with >5 activities
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT proj.DS_NOME_PROJETO, (SELECT COUNT(*) FROM TB_ATIVIDADE WHERE ID_PROJ_VINCULADO = proj.ID_PROJETO) AS TOTAL_ATIVIDADES
FROM TB_PROJETO_EXTENSAO proj
WHERE EXISTS (
    SELECT 1 FROM TB_ATIVIDADE a
    JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
    WHERE a.ID_PROJ_VINCULADO = proj.ID_PROJETO
    AND alloc.ID_INSTRUTOR = proj.ID_INSTR_COORDENADOR
)
AND proj.ID_PROJETO IN (
    SELECT ID_PROJ_VINCULADO
    FROM TB_ATIVIDADE
    GROUP BY ID_PROJ_VINCULADO
    HAVING COUNT(*) > 5
);

-- [RF7] Query 8: Projects with more than average 'ALUNO' participants
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, RL_MEMBRO_PROJETO, TB_PARTICIPANTE
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT proj.DS_NOME_PROJETO, COUNT(p.ID_PARTICIPANTE) AS TOTAL_ALUNOS
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
JOIN TB_PARTICIPANTE p ON mem.ID_PARTICIPANTE = p.ID_PARTICIPANTE
WHERE p.TP_VINCULO_INST = 'ALUNO'
GROUP BY proj.DS_NOME_PROJETO
HAVING COUNT(p.ID_PARTICIPANTE) > (
    SELECT AVG(alunos_count) FROM (
        SELECT COUNT(p2.ID_PARTICIPANTE) AS ALUNOS_COUNT
        FROM RL_MEMBRO_PROJETO mem2
        JOIN TB_PARTICIPANTE p2 ON mem2.ID_PARTICIPANTE = p2.ID_PARTICIPANTE
        WHERE p2.TP_VINCULO_INST = 'ALUNO'
        GROUP BY mem2.ID_PROJETO
    ) sub
);

-- [RF1] Query 9: Activities with more than 1 instructor and also have a partner sponsor
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR, RL_PATROCINIO_EVENTO
-- Funções: SUB-QUERY (IN + EXISTS), GROUP BY, COUNT (HAVING)
SELECT DS_TITULO_ATIVIDADE
FROM TB_ATIVIDADE a
WHERE ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_ALOCACAO_INSTRUTOR GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 1
) AND EXISTS (
    SELECT 1 FROM RL_PATROCINIO_EVENTO pat WHERE pat.ID_ATIVIDADE = a.ID_ATIVIDADE
);

-- [RF5] Query 10: Month-over-month growth of projects alongside total enrollments per project creation month
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_INSCRICAO_HISTORICO
-- Funções: JOIN, GROUP BY, WINDOW (SUM), COUNT
SELECT
    DATE_TRUNC('month', proj.DT_CRIACAO) AS MES_CRIACAO,
    COUNT(DISTINCT proj.ID_PROJETO) AS PROJETOS_NO_MES,
    COUNT(DISTINCT i.ID_INSCRICAO) AS TOTAL_INSCRICOES,
    SUM(COUNT(DISTINCT proj.ID_PROJETO)) OVER(ORDER BY DATE_TRUNC('month', proj.DT_CRIACAO)) AS PROJETOS_ACUMULADOS,
    COUNT(DISTINCT proj.ID_PROJETO) - COALESCE(LAG(COUNT(DISTINCT proj.ID_PROJETO)) OVER(ORDER BY DATE_TRUNC('month', proj.DT_CRIACAO)), 0) AS CRESCIMENTO_MENSAL
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
GROUP BY DATE_TRUNC('month', proj.DT_CRIACAO);

-- [RF4] Query 11: Find the activity with the highest average satisfaction rating
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK
-- Funções: SUB-QUERY, JOIN, GROUP BY
SELECT DS_TITULO_ATIVIDADE, media_satisfacao
FROM (
    SELECT a.DS_TITULO_ATIVIDADE, AVG(f.VL_NOTA_SATISFACAO) AS MEDIA_SATISFACAO
    FROM TB_ATIVIDADE a
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
    GROUP BY a.DS_TITULO_ATIVIDADE
) sub
ORDER BY media_satisfacao DESC
LIMIT 1;

-- [RF3] Query 12: Participants who have a certificate for every activity, with certificate count
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: SUB-QUERY (NOT EXISTS), JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE, COUNT(c.ID_CERTIFICADO) AS TOTAL_CERTIFICADOS
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_EMISSAO_CERTIFICADO c ON i.ID_INSCRICAO = c.ID_INSCRICAO
WHERE NOT EXISTS (
    SELECT 1 FROM RL_INSCRICAO_HISTORICO i2
    LEFT JOIN TB_EMISSAO_CERTIFICADO c2 ON i2.ID_INSCRICAO = c2.ID_INSCRICAO
    WHERE i2.ID_PARTICIPANTE = p.ID_PARTICIPANTE AND c2.ID_CERTIFICADO IS NULL
)
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE;

-- [RF2] Query 13: Super-participants (>5 enrollments) with activity details
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE, COUNT(i.ID_INSCRICAO) AS TOTAL_INSCRICOES
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE p.ID_PARTICIPANTE IN (
    SELECT i2.ID_PARTICIPANTE
    FROM RL_INSCRICAO_HISTORICO i2
    GROUP BY i2.ID_PARTICIPANTE
    HAVING COUNT(i2.ID_INSCRICAO) > 5
)
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE;

-- [RF1] Query 14: Projects and average workload, only projects above overall average workload
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT
    proj.DS_NOME_PROJETO,
    AVG(alloc.VL_CARGA_HORARIA) AS AVG_WORKLOAD,
    COUNT(DISTINCT a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
GROUP BY proj.ID_PROJETO, proj.DS_NOME_PROJETO
HAVING AVG(alloc.VL_CARGA_HORARIA) > (
    SELECT AVG(VL_CARGA_HORARIA) FROM RL_ALOCACAO_INSTRUTOR
);

-- [RF2] Query 15: First activity date for each participant, only those enrolled in >2 activities
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (FIRST_VALUE), SUB-QUERY
SELECT DISTINCT
    p.DS_NOME_PARTICIPANTE,
    FIRST_VALUE(a.DT_REALIZACAO) OVER(PARTITION BY p.ID_PARTICIPANTE ORDER BY a.DT_REALIZACAO) AS PRIMEIRA_ATIVIDADE
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE p.ID_PARTICIPANTE IN (
    SELECT i2.ID_PARTICIPANTE
    FROM RL_INSCRICAO_HISTORICO i2
    GROUP BY i2.ID_PARTICIPANTE
    HAVING COUNT(DISTINCT i2.ID_ATIVIDADE) > 1
);

-- [RF1] Query 16: Count activities by instructor specialty (>= 2 activities), ordered by highest count
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY, ORDER BY
SELECT inst.DS_ESPECIALIDADE, COUNT(DISTINCT a.ID_ATIVIDADE) AS TOTAL_ATIVIDADES
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE inst.DS_ESPECIALIDADE IN (
    SELECT inst2.DS_ESPECIALIDADE
    FROM TB_INSTRUTOR inst2
    JOIN RL_ALOCACAO_INSTRUTOR alloc2 ON inst2.ID_INSTRUTOR = alloc2.ID_INSTRUTOR
    GROUP BY inst2.DS_ESPECIALIDADE
    HAVING COUNT(DISTINCT alloc2.ID_ATIVIDADE) >= 2
)
GROUP BY inst.DS_ESPECIALIDADE
ORDER BY total_atividades DESC;

-- [RF4] Query 17: Participant with lowest feedback score in a highly attended activity (>20 people)
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK, TB_ATIVIDADE
-- Funções: SUB-QUERY, JOIN, GROUP BY (in sub-query), COUNT (HAVING)
SELECT p.DS_NOME_PARTICIPANTE, f.VL_NOTA_SATISFACAO, a.DS_TITULO_ATIVIDADE
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 20
)
ORDER BY f.VL_NOTA_SATISFACAO ASC
LIMIT 1;

-- [RF2] Query 18: Recent activities with enrollment counts, compared to overall average
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PARTICIPANTE
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
WITH RecentActivities AS (
    SELECT * FROM TB_ATIVIDADE WHERE DT_REALIZACAO >= CURRENT_DATE - INTERVAL '6 months'
)
SELECT
    ra.DS_TITULO_ATIVIDADE,
    ra.DT_REALIZACAO,
    COUNT(i.ID_INSCRICAO) AS TOTAL_INSCRITOS
FROM RecentActivities ra
JOIN RL_INSCRICAO_HISTORICO i ON ra.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON i.ID_PARTICIPANTE = p.ID_PARTICIPANTE
GROUP BY ra.ID_ATIVIDADE, ra.DS_TITULO_ATIVIDADE, ra.DT_REALIZACAO
HAVING COUNT(i.ID_INSCRICAO) > (
    SELECT AVG(cnt) FROM (
        SELECT COUNT(*) AS CNT FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE
    ) avg_sub
);

-- [RF5] Query 19: Partners who sponsor activities in more than one project, with total value
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT (HAVING), SUB-QUERY
SELECT p.DS_NOME_ORGANIZACAO, 
       (SELECT SUM(VL_APORTE) FROM RL_PATROCINIO_EVENTO pat2 WHERE pat2.ID_PARCEIRO = p.ID_PARCEIRO) AS TOTAL_APORTADO
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY p.ID_PARCEIRO, p.DS_NOME_ORGANIZACAO
HAVING COUNT(DISTINCT a.ID_PROJ_VINCULADO) > 1;

-- [RF6] Query 20: Difference between participant grade and activity average, for activities with >10 enrollments
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (AVG), SUB-QUERY
SELECT
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    i.VL_NOTA_AVALIACAO,
    i.VL_NOTA_AVALIACAO - AVG(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE) AS DIFF_PARA_MEDIA
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
    HAVING COUNT(*) > 10
);

-- IC Extension Management - Views for Reports (VW_)
-- Compliant with MAD1: VW_ prefix, simplify complex queries, restrict access

-- [RF5] VW_IMPACTO_PROJETO: Impact summary per project (enrollments, certificates, avg satisfaction)
CREATE OR REPLACE VIEW VW_IMPACTO_PROJETO AS SELECT
    proj.ID_PROJETO,
    proj.DS_NOME_PROJETO,
    COUNT(DISTINCT i.ID_INSCRICAO) AS TOTAL_INSCRICOES,
    COUNT(DISTINCT cert.ID_CERTIFICADO) AS TOTAL_CERTIFICADOS,
    ROUND(AVG(f.VL_NOTA_SATISFACAO), 2) AS MEDIA_SATISFACAO
FROM TB_PROJETO_EXTENSAO proj
LEFT JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
LEFT JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
LEFT JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
LEFT JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
GROUP BY proj.ID_PROJETO, proj.DS_NOME_PROJETO;

-- [RF2] VW_PARTICIPANTE_ATIVO: Participants with at least 1 presence
CREATE OR REPLACE VIEW VW_PARTICIPANTE_ATIVO AS SELECT
    p.ID_PARTICIPANTE,
    p.DS_NOME_PARTICIPANTE,
    p.DS_EMAIL_CONTATO,
    p.TP_VINCULO_INST,
    COUNT(i.ID_INSCRICAO) AS TOTAL_PRESENCAS
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
WHERE i.ST_PRESENCA = 'PRESENTE'
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE, p.DS_EMAIL_CONTATO, p.TP_VINCULO_INST;

-- [RF5] VW_PARCEIRO_APORTE: Partners and total sponsorship value
CREATE OR REPLACE VIEW VW_PARCEIRO_APORTE AS SELECT
    par.ID_PARCEIRO,
    par.DS_NOME_ORGANIZACAO,
    par.TP_PARCEIRO,
    COUNT(DISTINCT pat.ID_ATIVIDADE) AS TOTAL_ATIVIDADES_APOIADAS,
    COALESCE(SUM(pat.VL_APORTE), 0) AS TOTAL_APORTADO
FROM TB_PARCEIRO par
LEFT JOIN RL_PATROCINIO_EVENTO pat ON par.ID_PARCEIRO = pat.ID_PARCEIRO
GROUP BY par.ID_PARCEIRO, par.DS_NOME_ORGANIZACAO, par.TP_PARCEIRO;

-- [RF3] VW_CERTIFICADO_EMITIDO: All issued certificates with participant and activity
CREATE OR REPLACE VIEW VW_CERTIFICADO_EMITIDO AS SELECT
    cert.ID_CERTIFICADO,
    cert.CD_AUTENTICIDADE,
    cert.DT_EMISSAO,
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    a.DT_REALIZACAO
FROM TB_EMISSAO_CERTIFICADO cert
JOIN RL_INSCRICAO_HISTORICO i ON cert.ID_INSCRICAO = i.ID_INSCRICAO
JOIN TB_PARTICIPANTE p ON i.ID_PARTICIPANTE = p.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE;

-- Grant SELECT on views to analise_ic role
GRANT SELECT ON VW_IMPACTO_PROJETO TO analise_ic;
GRANT SELECT ON VW_PARTICIPANTE_ATIVO TO analise_ic;
GRANT SELECT ON VW_PARCEIRO_APORTE TO analise_ic;
GRANT SELECT ON VW_CERTIFICADO_EMITIDO TO analise_ic;

-- IC Extension Management - Backup Procedures (PBR1)
-- Compliant with PBR1: Full backup weekly, integrity tests daily, restore tests monthly
-- Storage: Local (/var/backup/ic_extensao) and remote (Drive, GitHub, Dropbox, etc.)
-- DBMS: PostgreSQL

-- 1. Function to perform full backup
CREATE OR REPLACE FUNCTION SP_EXECUTAR_BACKUP_FULL()
RETURNS TEXT AS $$
DECLARE
    v_backup_dir TEXT := '/var/backup/ic_extensao';
    v_remote_dir TEXT := '/mnt/remote_backup/ic_extensao';
    v_backup_file TEXT;
    v_remote_file TEXT;
    v_timestamp TEXT;
    v_result TEXT;
BEGIN
    v_timestamp := TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD_HH24MISS');
    v_backup_file := v_backup_dir || '/ic_extensao_full_' || v_timestamp || '.backup';
    v_remote_file := v_remote_dir || '/ic_extensao_full_' || v_timestamp || '.backup';

    -- Execute pg_dump via pg_read_file is not possible; this function documents the procedure
    -- Actual execution must be done via pg_dump command-line or pg_cron job:
    -- Local: pg_dump -U dbbackup_ic -Fc -b -v -f <backup_file> ic_extensao
    -- Remote: pg_dump -U dbbackup_ic -Fc -b -v -f <remote_file> ic_extensao
    -- Cloud sync: gdrive upload <backup_file> (or rsync to remote storage)

    INSERT INTO TL_LOG_BACKUP (DS_ARQUIVO, DH_INICIO, ST_RESULTADO)
    VALUES (v_backup_file, CURRENT_TIMESTAMP, 'EXECUTADO');

    INSERT INTO TL_LOG_BACKUP (DS_ARQUIVO, DH_INICIO, ST_RESULTADO)
    VALUES (v_remote_file, CURRENT_TIMESTAMP, 'ARMAZENADO');

    RETURN 'Backup completed (local + remote): ' || v_backup_file;
END;
$$ LANGUAGE plpgsql;

-- 2. Log table for backup operations
CREATE TABLE TL_LOG_BACKUP (
    ID_LOG_BACKUP SERIAL PRIMARY KEY,
    DS_ARQUIVO VARCHAR(500),
    DH_INICIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DH_FIM TIMESTAMP,
    ST_RESULTADO VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
    DS_ERRO TEXT
);

-- 3. Function to register backup completion
CREATE OR REPLACE FUNCTION SP_REGISTRAR_BACKUP(
    p_arquivo VARCHAR(500),
    p_resultado VARCHAR(30),
    p_erro TEXT DEFAULT NULL
) RETURNS INT AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO TL_LOG_BACKUP (DS_ARQUIVO, DH_INICIO, DH_FIM, ST_RESULTADO, DS_ERRO)
    VALUES (p_arquivo, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, p_resultado, p_erro)
    RETURNING ID_LOG_BACKUP INTO v_id;

    RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- 4. Function to test backup integrity (simulated)
CREATE OR REPLACE FUNCTION SP_TESTAR_INTEGRIDADE_BACKUP()
RETURNS TABLE (
    DH_VERIFICACAO TIMESTAMP,
    ST_INTEGRIDADE VARCHAR(30),
    DS_OBSERVACAO TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        CURRENT_TIMESTAMP AS DH_VERIFICACAO,
        'OK'::VARCHAR(30) AS ST_INTEGRIDADE,
        'Verificacao de integridade realizada com sucesso. Logs de backup sem erros.'::TEXT AS DS_OBSERVACAO;
END;
$$ LANGUAGE plpgsql;

-- 5. Grant backup role extra permissions (beyond SELECT granted above)
GRANT EXECUTE ON FUNCTION SP_EXECUTAR_BACKUP_FULL() TO dbbackup_ic;
GRANT EXECUTE ON FUNCTION SP_REGISTRAR_BACKUP(VARCHAR, VARCHAR, TEXT) TO dbbackup_ic;
GRANT EXECUTE ON FUNCTION SP_TESTAR_INTEGRIDADE_BACKUP() TO dbbackup_ic;
GRANT ALL PRIVILEGES ON TL_LOG_BACKUP TO dbbackup_ic;

