-- IC Extension Management Database Initialization
-- Physical Schema based on Logical Model
-- DBMS: PostgreSQL

-- 1. Base Tables (TB_)

CREATE TABLE TB_INSTRUTOR (
    ID_INSTRUTOR SERIAL PRIMARY KEY,
    DS_NOME_INSTRUTOR VARCHAR(150) NOT NULL,
    DS_ESPECIALIDADE VARCHAR(100)
);

CREATE TABLE TB_PROJETO_EXTENSAO (
    ID_PROJETO SERIAL PRIMARY KEY,
    DS_NOME_PROJETO VARCHAR(150) NOT NULL,
    DT_CRIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_INSTR_COORDENADOR INT NOT NULL,
    CONSTRAINT FK_PROJETO_COORDENADOR FOREIGN KEY (ID_INSTR_COORDENADOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR)
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL PRIMARY KEY,
    DS_TITULO_ATIVIDADE VARCHAR(150) NOT NULL,
    DS_CONTEUDO_PROG TEXT,
    DT_REALIZACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_PROJ_VINCULADO INT,
    CONSTRAINT FK_ATIVIDADE_PROJETO FOREIGN KEY (ID_PROJ_VINCULADO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);

CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE SERIAL PRIMARY KEY,
    DS_NOME_PARTICIPANTE VARCHAR(150) NOT NULL,
    DS_EMAIL_CONTATO VARCHAR(100) NOT NULL,
    TP_VINCULO_INST VARCHAR(30) NOT NULL
);

CREATE TABLE TB_PARCEIRO (
    ID_PARCEIRO SERIAL PRIMARY KEY,
    DS_NOME_ORGANIZACAO VARCHAR(150) NOT NULL,
    TP_PARCEIRO VARCHAR(30) NOT NULL
);

-- 2. Associative Tables (RL_)

CREATE TABLE RL_INSCRICAO_HISTORICO (
    ID_INSCRICAO SERIAL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    ST_PRESENCA VARCHAR(20) NOT NULL CHECK (ST_PRESENCA IN ('PRESENTE', 'AUSENTE')),
    VL_NOTA_AVALIACAO DECIMAL(4,2) CHECK (VL_NOTA_AVALIACAO BETWEEN 0 AND 10),
    CONSTRAINT FK_INSCRICAO_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_INSCRICAO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE TB_EMISSAO_CERTIFICADO (
    ID_CERTIFICADO SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL UNIQUE,
    DT_EMISSAO DATE NOT NULL DEFAULT CURRENT_DATE,
    CD_AUTENTICIDADE VARCHAR(60) NOT NULL UNIQUE,
    CONSTRAINT FK_CERTIFICADO_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE TB_REGISTRO_FEEDBACK (
    ID_FEEDBACK SERIAL PRIMARY KEY,
    ID_INSCRICAO INT NOT NULL UNIQUE,
    VL_NOTA_SATISFACAO INT NOT NULL CHECK (VL_NOTA_SATISFACAO BETWEEN 1 AND 5),
    DS_COMENTARIO_ABERTO TEXT,
    CONSTRAINT FK_FEEDBACK_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES RL_INSCRICAO_HISTORICO(ID_INSCRICAO)
);

CREATE TABLE RL_ALOCACAO_INSTRUTOR (
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    VL_CARGA_HORARIA INT NOT NULL,
    PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR),
    CONSTRAINT FK_ALOCACAO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE),
    CONSTRAINT FK_ALOCACAO_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR) REFERENCES TB_INSTRUTOR(ID_INSTRUTOR)
);

CREATE TABLE RL_PATROCINIO_EVENTO (
    ID_PARCEIRO INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    VL_APORTE DECIMAL(12,2),
    PRIMARY KEY (ID_PARCEIRO, ID_ATIVIDADE),
    CONSTRAINT FK_PATROCINIO_PARCEIRO FOREIGN KEY (ID_PARCEIRO) REFERENCES TB_PARCEIRO(ID_PARCEIRO),
    CONSTRAINT FK_PATROCINIO_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE RL_MEMBRO_PROJETO (
    ID_PARTICIPANTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    TP_PAPEL_ATUACAO VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_PARTICIPANTE, ID_PROJETO),
    CONSTRAINT FK_MEMBRO_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
    CONSTRAINT FK_MEMBRO_PROJETO FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO)
);


-- IC Extension Management - Data Population Script
-- DBMS: PostgreSQL

-- 1. Auxiliary Tables

-- TB_INSTRUTOR: 50 records
INSERT INTO TB_INSTRUTOR (DS_NOME_INSTRUTOR, DS_ESPECIALIDADE)
SELECT 'Instrutor ' || i, 'Especialidade ' || (i % 5 + 1)
FROM generate_series(1, 50) s(i);

-- TB_PARCEIRO: 20 records
INSERT INTO TB_PARCEIRO (DS_NOME_ORGANIZACAO, TP_PARCEIRO)
SELECT 'Parceiro ' || i, CASE WHEN i % 3 = 0 THEN 'ONG' WHEN i % 3 = 1 THEN 'Empresa Privada' ELSE 'Órgão Público' END
FROM generate_series(1, 20) s(i);

-- TB_PROJETO_EXTENSAO: 10 records
INSERT INTO TB_PROJETO_EXTENSAO (DS_NOME_PROJETO, DT_CRIACAO, ID_INSTR_COORDENADOR)
SELECT 'Projeto de Extensão ' || i, CURRENT_DATE - (i || ' months')::interval, (i % 50) + 1
FROM generate_series(1, 10) s(i);

-- TB_ATIVIDADE: 100 records
INSERT INTO TB_ATIVIDADE (DS_TITULO_ATIVIDADE, DS_CONTEUDO_PROG, DT_REALIZACAO, ID_PROJ_VINCULADO)
SELECT 'Atividade ' || i, 'Conteúdo programático da atividade ' || i, CURRENT_DATE + (i || ' days')::interval, (i % 10) + 1
FROM generate_series(1, 100) s(i);

-- 2. Core Data (5,500 Participants)
INSERT INTO TB_PARTICIPANTE (DS_NOME_PARTICIPANTE, DS_EMAIL_CONTATO, TP_VINCULO_INST)
SELECT 
    'Participante ' || i, 
    'user' || i || '@example.com', 
    CASE WHEN i % 3 = 0 THEN 'ALUNO' WHEN i % 3 = 1 THEN 'COMUNIDADE' ELSE 'SERVIDOR' END
FROM generate_series(1, 5500) s(i);

-- 3. Relationships (11,000 Enrollments)
INSERT INTO RL_INSCRICAO_HISTORICO (ID_PARTICIPANTE, ID_ATIVIDADE, ST_PRESENCA, VL_NOTA_AVALIACAO)
SELECT 
    p.id, 
    (random() * 99)::int + 1, 
    CASE WHEN random() > 0.2 THEN 'PRESENTE' ELSE 'AUSENTE' END,
    (random() * 10)::decimal(4,2)
FROM generate_series(1, 5500) s(i), LATERAL (SELECT i as id) p
CROSS JOIN generate_series(1, 2) g(j);

-- 4. Other Relationships

-- RL_ALOCACAO_INSTRUTOR: ~200 records
INSERT INTO RL_ALOCACAO_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, VL_CARGA_HORARIA)
SELECT 
    a.id, 
    (random() * 49)::int + 1, 
    (random() * 10 + 2)::int
FROM generate_series(1, 100) s(i), LATERAL (SELECT i as id) a
CROSS JOIN generate_series(1, 2) g(j)
ON CONFLICT DO NOTHING;

-- RL_PATROCINIO_EVENTO: ~50 records
INSERT INTO RL_PATROCINIO_EVENTO (ID_PARCEIRO, ID_ATIVIDADE, VL_APORTE)
SELECT 
    (random() * 19)::int + 1, 
    (random() * 99)::int + 1, 
    (random() * 5000 + 500)::decimal(12,2)
FROM generate_series(1, 50) s(i)
ON CONFLICT DO NOTHING;

-- RL_MEMBRO_PROJETO: ~300 records
INSERT INTO RL_MEMBRO_PROJETO (ID_PARTICIPANTE, ID_PROJETO, TP_PAPEL_ATUACAO)
SELECT 
    (random() * 5499)::int + 1, 
    (random() * 9)::int + 1, 
    CASE WHEN random() > 0.5 THEN 'Bolsista' ELSE 'Voluntário' END
FROM generate_series(1, 300) s(i)
ON CONFLICT DO NOTHING;


-- IC Extension Management - Indexing Plan
-- DBMS: PostgreSQL

-- 1. Indexing Foreign Keys for Faster Joins

CREATE INDEX IDX_PROJETO_COORDENADOR ON TB_PROJETO_EXTENSAO(ID_INSTR_COORDENADOR);
CREATE INDEX IDX_ATIVIDADE_PROJETO ON TB_ATIVIDADE(ID_PROJ_VINCULADO);
CREATE INDEX IDX_INSCRICAO_PARTICIPANTE ON RL_INSCRICAO_HISTORICO(ID_PARTICIPANTE);
CREATE INDEX IDX_INSCRICAO_ATIVIDADE ON RL_INSCRICAO_HISTORICO(ID_ATIVIDADE);
CREATE INDEX IDX_CERTIFICADO_INSCRICAO ON TB_EMISSAO_CERTIFICADO(ID_INSCRICAO);
CREATE INDEX IDX_FEEDBACK_INSCRICAO ON TB_REGISTRO_FEEDBACK(ID_INSCRICAO);

-- 2. Indexing Columns used in WHERE and GROUP BY filters

CREATE INDEX IDX_PARTICIPANTE_EMAIL ON TB_PARTICIPANTE(DS_EMAIL_CONTATO);
CREATE INDEX IDX_INSCRICAO_PRESENCA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA);
CREATE INDEX IDX_ATIVIDADE_DATA ON TB_ATIVIDADE(DT_REALIZACAO);

-- 3. Composite Indexes for specific query optimization

-- Speed up queries that filter by presence and need the grade
CREATE INDEX IDX_INSCRICAO_PRESENCA_NOTA ON RL_INSCRICAO_HISTORICO(ST_PRESENCA, VL_NOTA_AVALIACAO);


-- IC Extension Management - Intermediate Queries (10)
-- Requirements: RF1-RF7 (Activity management, enrollment, certificates, feedback, partnerships, grades, projects)
-- Criteria: ≥3 distinct base tables, ≥2 of: JOIN, GROUP BY, WINDOW functions, COUNT

-- [RF2] Query 1: Count enrollments per participant in activities of project 1
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE, TB_PROJETO_EXTENSAO
-- Funções: JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE,
       proj.DS_NOME_PROJETO,
       COUNT(i.ID_INSCRICAO) AS total_inscricoes
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
WHERE proj.ID_PROJETO = 1
GROUP BY p.DS_NOME_PARTICIPANTE, proj.DS_NOME_PROJETO;

-- [RF1] Query 2: Count the number of activities per project with coordinator name
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, TB_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT
SELECT proj.DS_NOME_PROJETO,
       inst.DS_NOME_INSTRUTOR AS coordenador,
       COUNT(a.ID_ATIVIDADE) AS total_atividades
FROM TB_PROJETO_EXTENSAO proj
LEFT JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN TB_INSTRUTOR inst ON proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
GROUP BY proj.DS_NOME_PROJETO, inst.DS_NOME_INSTRUTOR;

-- [RF1] Query 3: List instructors and total workload with activity context
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, SUM, COUNT
SELECT inst.DS_NOME_INSTRUTOR,
       COUNT(a.ID_ATIVIDADE) AS total_atividades,
       SUM(alloc.VL_CARGA_HORARIA) AS total_horas
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY inst.DS_NOME_INSTRUTOR;

-- [RF5] Query 4: List partners, total contributions, and sponsored activities
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, SUM, COUNT
SELECT part.DS_NOME_ORGANIZACAO,
       COUNT(a.ID_ATIVIDADE) AS total_atividades_patrocinadas,
       SUM(pat.VL_APORTE) AS total_patrocinio
FROM TB_PARCEIRO part
JOIN RL_PATROCINIO_EVENTO pat ON part.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY part.DS_NOME_ORGANIZACAO;

-- [RF2] Query 5: Participants attending ≥2 activities, showing activity names
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT, HAVING
SELECT p.DS_NOME_PARTICIPANTE,
       COUNT(a.ID_ATIVIDADE) AS total_presencas
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE i.ST_PRESENCA = 'PRESENTE'
GROUP BY p.DS_NOME_PARTICIPANTE
HAVING COUNT(a.ID_ATIVIDADE) >= 2;

-- [RF6] Query 6: Average grade per activity with project context
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PROJETO_EXTENSAO
-- Funções: JOIN, GROUP BY, AVG, COUNT
SELECT a.DS_TITULO_ATIVIDADE,
       proj.DS_NOME_PROJETO,
       AVG(i.VL_NOTA_AVALIACAO) AS media_nota,
       COUNT(i.ID_INSCRICAO) AS total_inscricoes
FROM TB_ATIVIDADE a
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
GROUP BY a.DS_TITULO_ATIVIDADE, proj.DS_NOME_PROJETO
HAVING COUNT(i.ID_INSCRICAO) > 5;

-- [RF7] Query 7: Count activities coordinated per instructor
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_ATIVIDADE, TB_PROJETO_EXTENSAO, TB_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT
SELECT inst.DS_NOME_INSTRUTOR,
       COUNT(a.ID_ATIVIDADE) AS total_atividades_coordenadas
FROM TB_ATIVIDADE a
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
JOIN TB_INSTRUTOR inst ON proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
GROUP BY inst.DS_NOME_INSTRUTOR;

-- [RF3] Query 8: Count certificates issued per activity
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: JOIN, GROUP BY, COUNT
SELECT a.DS_TITULO_ATIVIDADE, COUNT(cert.ID_CERTIFICADO) AS total_certificados
FROM TB_ATIVIDADE a
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
GROUP BY a.DS_TITULO_ATIVIDADE;

-- [RF4] Query 9: Count feedbacks and average satisfaction per participant
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK
-- Funções: JOIN, GROUP BY, COUNT, AVG
SELECT p.DS_NOME_PARTICIPANTE,
       COUNT(f.ID_FEEDBACK) AS total_feedbacks,
       AVG(f.VL_NOTA_SATISFACAO) AS media_satisfacao
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
GROUP BY p.DS_NOME_PARTICIPANTE;

-- [RF7] Query 10: List projects and total members with participant names
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, RL_MEMBRO_PROJETO, TB_PARTICIPANTE
-- Funções: JOIN, GROUP BY, COUNT
SELECT proj.DS_NOME_PROJETO,
       COUNT(mem.ID_PARTICIPANTE) AS total_membros
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
JOIN TB_PARTICIPANTE p ON mem.ID_PARTICIPANTE = p.ID_PARTICIPANTE
GROUP BY proj.DS_NOME_PROJETO;


-- IC Extension Management - Advanced Queries (20)
-- Requirements: 3+ tables, 3+ of: Sub-queries, JOIN, GROUP BY, Window functions, COUNT

-- [RF6] Query 1: Rank participants by average grade across all activities
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, WINDOW (RANK)
SELECT
    sub.DS_NOME_PARTICIPANTE,
    sub.media_global,
    RANK() OVER(ORDER BY sub.media_global DESC) as ranking
FROM (
    SELECT
        p.ID_PARTICIPANTE,
        p.DS_NOME_PARTICIPANTE,
        AVG(i.VL_NOTA_AVALIACAO) as media_global
    FROM TB_PARTICIPANTE p
    JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
    JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
    GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE
) sub;

-- [RF3] Query 2: Find the top 3 projects by total number of certificates issued
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
SELECT DS_NOME_PROJETO, total_certificados
FROM (
    SELECT proj.DS_NOME_PROJETO, COUNT(cert.ID_CERTIFICADO) as total_certificados
    FROM TB_PROJETO_EXTENSAO proj
    JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_EMISSAO_CERTIFICADO cert ON i.ID_INSCRICAO = cert.ID_INSCRICAO
    GROUP BY proj.DS_NOME_PROJETO
) sub
ORDER BY total_certificados DESC
LIMIT 3;

-- [RF2] Query 3: Activities with participation higher than the average, showing project name
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PROJETO_EXTENSAO
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
WITH AtividadeContagem AS (
    SELECT ID_ATIVIDADE, COUNT(*) as total_inscritos
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
)
SELECT a.DS_TITULO_ATIVIDADE, proj.DS_NOME_PROJETO, ac.total_inscritos
FROM TB_ATIVIDADE a
JOIN AtividadeContagem ac ON a.ID_ATIVIDADE = ac.ID_ATIVIDADE
JOIN TB_PROJETO_EXTENSAO proj ON a.ID_PROJ_VINCULADO = proj.ID_PROJETO
WHERE ac.total_inscritos > (SELECT AVG(total_inscritos) FROM AtividadeContagem);

-- [RF7] Query 4: Instructors who never coordinated a project but are allocated to activities
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE, TB_PROJETO_EXTENSAO
-- Funções: SUB-QUERY (NOT EXISTS), JOIN, GROUP BY, COUNT
SELECT
    inst.DS_NOME_INSTRUTOR,
    COUNT(DISTINCT alloc.ID_ATIVIDADE) as total_atividades_alocadas
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE NOT EXISTS (
    SELECT 1 FROM TB_PROJETO_EXTENSAO proj
    WHERE proj.ID_INSTR_COORDENADOR = inst.ID_INSTRUTOR
)
GROUP BY inst.ID_INSTRUTOR, inst.DS_NOME_INSTRUTOR;

-- [RF5] Query 5: Running total of sponsorship contributions per partner with activity names
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (SUM), COUNT
SELECT
    p.DS_NOME_ORGANIZACAO,
    a.DS_TITULO_ATIVIDADE,
    pat.VL_APORTE,
    SUM(pat.VL_APORTE) OVER(PARTITION BY p.ID_PARCEIRO ORDER BY a.ID_ATIVIDADE) as total_acumulado,
    COUNT(*) OVER(PARTITION BY p.ID_PARCEIRO) as total_patrocinios_parceiro
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE;

-- [RF6] Query 6: Participant grade as percentage of max grade, only for activities with >5 enrollments
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW, SUB-QUERY
SELECT
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    i.VL_NOTA_AVALIACAO,
    (i.VL_NOTA_AVALIACAO / MAX(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE)) * 100 as perc_max_nota
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
    HAVING COUNT(*) > 5
);

-- [RF7] Query 7: Projects where the coordinator also teaches, only projects with >5 activities
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT proj.DS_NOME_PROJETO, COUNT(DISTINCT a.ID_ATIVIDADE) as total_atividades
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
WHERE alloc.ID_INSTRUTOR = proj.ID_INSTR_COORDENADOR
AND proj.ID_PROJETO IN (
    SELECT ID_PROJ_VINCULADO
    FROM TB_ATIVIDADE
    GROUP BY ID_PROJ_VINCULADO
    HAVING COUNT(*) > 5
)
GROUP BY proj.DS_NOME_PROJETO;

-- [RF7] Query 8: Projects with more than average 'ALUNO' participants
-- Requisito: RF7 - Extension project management (members, coordinators)
-- Tabelas: TB_PROJETO_EXTENSAO, RL_MEMBRO_PROJETO, TB_PARTICIPANTE
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT proj.DS_NOME_PROJETO, COUNT(p.ID_PARTICIPANTE) as total_alunos
FROM TB_PROJETO_EXTENSAO proj
JOIN RL_MEMBRO_PROJETO mem ON proj.ID_PROJETO = mem.ID_PROJETO
JOIN TB_PARTICIPANTE p ON mem.ID_PARTICIPANTE = p.ID_PARTICIPANTE
WHERE p.TP_VINCULO_INST = 'ALUNO'
GROUP BY proj.DS_NOME_PROJETO
HAVING COUNT(p.ID_PARTICIPANTE) > (
    SELECT AVG(alunos_count) FROM (
        SELECT COUNT(p2.ID_PARTICIPANTE) as alunos_count
        FROM RL_MEMBRO_PROJETO mem2
        JOIN TB_PARTICIPANTE p2 ON mem2.ID_PARTICIPANTE = p2.ID_PARTICIPANTE
        WHERE p2.TP_VINCULO_INST = 'ALUNO'
        GROUP BY mem2.ID_PROJETO
    ) sub
);

-- [RF1] Query 9: Activities with more than 1 instructor and also have a partner sponsor
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR, RL_PATROCINIO_EVENTO
-- Funções: SUB-QUERY (IN + EXISTS), GROUP BY, COUNT (HAVING)
SELECT DS_TITULO_ATIVIDADE
FROM TB_ATIVIDADE a
WHERE ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_ALOCACAO_INSTRUTOR GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 1
) AND EXISTS (
    SELECT 1 FROM RL_PATROCINIO_EVENTO pat WHERE pat.ID_ATIVIDADE = a.ID_ATIVIDADE
);

-- [RF5] Query 10: Month-over-month growth of projects alongside total enrollments per project creation month
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_INSCRICAO_HISTORICO
-- Funções: JOIN, GROUP BY, WINDOW (SUM), COUNT
SELECT
    DATE_TRUNC('month', proj.DT_CRIACAO) as mes_criacao,
    COUNT(DISTINCT proj.ID_PROJETO) as projetos_no_mes,
    COUNT(DISTINCT i.ID_INSCRICAO) as total_inscricoes,
    SUM(COUNT(DISTINCT proj.ID_PROJETO)) OVER(ORDER BY DATE_TRUNC('month', proj.DT_CRIACAO)) as projetos_acumulados
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
GROUP BY DATE_TRUNC('month', proj.DT_CRIACAO);

-- [RF4] Query 11: Find the activity with the highest average satisfaction rating
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK
-- Funções: SUB-QUERY, JOIN, GROUP BY
SELECT DS_TITULO_ATIVIDADE, media_satisfacao
FROM (
    SELECT a.DS_TITULO_ATIVIDADE, AVG(f.VL_NOTA_SATISFACAO) as media_satisfacao
    FROM TB_ATIVIDADE a
    JOIN RL_INSCRICAO_HISTORICO i ON a.ID_ATIVIDADE = i.ID_ATIVIDADE
    JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
    GROUP BY a.DS_TITULO_ATIVIDADE
) sub
ORDER BY media_satisfacao DESC
LIMIT 1;

-- [RF3] Query 12: Participants who have a certificate for every activity, with certificate count
-- Requisito: RF3 - Automatic certificate issuance after activity completion
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_EMISSAO_CERTIFICADO
-- Funções: SUB-QUERY (NOT EXISTS), JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE, COUNT(c.ID_CERTIFICADO) as total_certificados
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_EMISSAO_CERTIFICADO c ON i.ID_INSCRICAO = c.ID_INSCRICAO
WHERE NOT EXISTS (
    SELECT 1 FROM RL_INSCRICAO_HISTORICO i2
    LEFT JOIN TB_EMISSAO_CERTIFICADO c2 ON i2.ID_INSCRICAO = c2.ID_INSCRICAO
    WHERE i2.ID_PARTICIPANTE = p.ID_PARTICIPANTE AND c2.ID_CERTIFICADO IS NULL
)
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE;

-- [RF2] Query 13: Super-participants (>5 enrollments) with activity details
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
SELECT p.DS_NOME_PARTICIPANTE, COUNT(i.ID_INSCRICAO) as total_inscricoes
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE p.ID_PARTICIPANTE IN (
    SELECT i2.ID_PARTICIPANTE
    FROM RL_INSCRICAO_HISTORICO i2
    GROUP BY i2.ID_PARTICIPANTE
    HAVING COUNT(i2.ID_INSCRICAO) > 5
)
GROUP BY p.ID_PARTICIPANTE, p.DS_NOME_PARTICIPANTE;

-- [RF1] Query 14: Projects and average workload, only projects above overall average workload
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_PROJETO_EXTENSAO, TB_ATIVIDADE, RL_ALOCACAO_INSTRUTOR
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT
    proj.DS_NOME_PROJETO,
    AVG(alloc.VL_CARGA_HORARIA) as avg_workload,
    COUNT(DISTINCT a.ID_ATIVIDADE) as total_atividades
FROM TB_PROJETO_EXTENSAO proj
JOIN TB_ATIVIDADE a ON proj.ID_PROJETO = a.ID_PROJ_VINCULADO
JOIN RL_ALOCACAO_INSTRUTOR alloc ON a.ID_ATIVIDADE = alloc.ID_ATIVIDADE
GROUP BY proj.ID_PROJETO, proj.DS_NOME_PROJETO
HAVING AVG(alloc.VL_CARGA_HORARIA) > (
    SELECT AVG(VL_CARGA_HORARIA) FROM RL_ALOCACAO_INSTRUTOR
);

-- [RF2] Query 15: First activity date for each participant, only those enrolled in >2 activities
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (FIRST_VALUE), SUB-QUERY
SELECT DISTINCT
    p.DS_NOME_PARTICIPANTE,
    FIRST_VALUE(a.DT_REALIZACAO) OVER(PARTITION BY p.ID_PARTICIPANTE ORDER BY a.DT_REALIZACAO) as primeira_atividade
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE p.ID_PARTICIPANTE IN (
    SELECT i2.ID_PARTICIPANTE
    FROM RL_INSCRICAO_HISTORICO i2
    GROUP BY i2.ID_PARTICIPANTE
    HAVING COUNT(DISTINCT i2.ID_ATIVIDADE) > 2
);

-- [RF1] Query 16: Count activities by instructor specialty, bridged through TB_ATIVIDADE
-- Requisito: RF1 - Manage extension activities (dates, speakers, content)
-- Tabelas: TB_INSTRUTOR, RL_ALOCACAO_INSTRUTOR, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT, SUB-QUERY
SELECT inst.DS_ESPECIALIDADE, COUNT(DISTINCT a.ID_ATIVIDADE) as total_atividades
FROM TB_INSTRUTOR inst
JOIN RL_ALOCACAO_INSTRUTOR alloc ON inst.ID_INSTRUTOR = alloc.ID_INSTRUTOR
JOIN TB_ATIVIDADE a ON alloc.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE inst.DS_ESPECIALIDADE IN (
    SELECT inst2.DS_ESPECIALIDADE
    FROM TB_INSTRUTOR inst2
    JOIN RL_ALOCACAO_INSTRUTOR alloc2 ON inst2.ID_INSTRUTOR = alloc2.ID_INSTRUTOR
    GROUP BY inst2.DS_ESPECIALIDADE
    HAVING COUNT(DISTINCT alloc2.ID_ATIVIDADE) > 1
)
GROUP BY inst.DS_ESPECIALIDADE;

-- [RF4] Query 17: Participant with lowest feedback score in a highly attended activity (>20 people)
-- Requisito: RF4 - Participant feedback registration
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_REGISTRO_FEEDBACK, TB_ATIVIDADE
-- Funções: SUB-QUERY, JOIN, GROUP BY (in sub-query), COUNT (HAVING)
SELECT p.DS_NOME_PARTICIPANTE, f.VL_NOTA_SATISFACAO, a.DS_TITULO_ATIVIDADE
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_REGISTRO_FEEDBACK f ON i.ID_INSCRICAO = f.ID_INSCRICAO
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE HAVING COUNT(*) > 20
)
ORDER BY f.VL_NOTA_SATISFACAO ASC
LIMIT 1;

-- [RF2] Query 18: Recent activities with enrollment counts, compared to overall average
-- Requisito: RF2 - Enrollment, attendance control, participation history
-- Tabelas: TB_ATIVIDADE, RL_INSCRICAO_HISTORICO, TB_PARTICIPANTE
-- Funções: SUB-QUERY, JOIN, GROUP BY, COUNT
WITH RecentActivities AS (
    SELECT * FROM TB_ATIVIDADE WHERE DT_REALIZACAO >= CURRENT_DATE - INTERVAL '6 months'
)
SELECT
    ra.DS_TITULO_ATIVIDADE,
    ra.DT_REALIZACAO,
    COUNT(i.ID_INSCRICAO) as total_inscritos
FROM RecentActivities ra
JOIN RL_INSCRICAO_HISTORICO i ON ra.ID_ATIVIDADE = i.ID_ATIVIDADE
JOIN TB_PARTICIPANTE p ON i.ID_PARTICIPANTE = p.ID_PARTICIPANTE
GROUP BY ra.ID_ATIVIDADE, ra.DS_TITULO_ATIVIDADE, ra.DT_REALIZACAO
HAVING COUNT(i.ID_INSCRICAO) > (
    SELECT AVG(cnt) FROM (
        SELECT COUNT(*) as cnt FROM RL_INSCRICAO_HISTORICO GROUP BY ID_ATIVIDADE
    ) avg_sub
);

-- [RF5] Query 19: Partners who sponsor activities in more than one project, with total value
-- Requisito: RF5 - Partnership management, impact/participation reports
-- Tabelas: TB_PARCEIRO, RL_PATROCINIO_EVENTO, TB_ATIVIDADE
-- Funções: JOIN, GROUP BY, COUNT (HAVING), SUB-QUERY
SELECT p.DS_NOME_ORGANIZACAO, 
       (SELECT SUM(VL_APORTE) FROM RL_PATROCINIO_EVENTO pat2 WHERE pat2.ID_PARCEIRO = p.ID_PARCEIRO) as total_aportado
FROM TB_PARCEIRO p
JOIN RL_PATROCINIO_EVENTO pat ON p.ID_PARCEIRO = pat.ID_PARCEIRO
JOIN TB_ATIVIDADE a ON pat.ID_ATIVIDADE = a.ID_ATIVIDADE
GROUP BY p.ID_PARCEIRO, p.DS_NOME_ORGANIZACAO
HAVING COUNT(DISTINCT a.ID_PROJ_VINCULADO) > 1;

-- [RF6] Query 20: Difference between participant grade and activity average, for activities with >10 enrollments
-- Requisito: RF6 - Grade control for extension courses
-- Tabelas: TB_PARTICIPANTE, RL_INSCRICAO_HISTORICO, TB_ATIVIDADE
-- Funções: JOIN, WINDOW (AVG), SUB-QUERY
SELECT
    p.DS_NOME_PARTICIPANTE,
    a.DS_TITULO_ATIVIDADE,
    i.VL_NOTA_AVALIACAO,
    i.VL_NOTA_AVALIACAO - AVG(i.VL_NOTA_AVALIACAO) OVER(PARTITION BY a.ID_ATIVIDADE) as diff_para_media
FROM TB_PARTICIPANTE p
JOIN RL_INSCRICAO_HISTORICO i ON p.ID_PARTICIPANTE = i.ID_PARTICIPANTE
JOIN TB_ATIVIDADE a ON i.ID_ATIVIDADE = a.ID_ATIVIDADE
WHERE a.ID_ATIVIDADE IN (
    SELECT ID_ATIVIDADE
    FROM RL_INSCRICAO_HISTORICO
    GROUP BY ID_ATIVIDADE
    HAVING COUNT(*) > 10
);


